{
  "protocol": "rest",
  "title": "Campaign Manager 360 API",
  "canonicalName": "Dfareporting",
  "version": "v3.5",
  "servicePath": "dfareporting/v3.5/",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "revision": "20230210",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "id": "dfareporting:v3.5",
  "ownerDomain": "google.com",
  "basePath": "/dfareporting/v3.5/",
  "name": "dfareporting",
  "resources": {
    "advertisers": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser.",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.update",
          "path": "userprofiles/{profileId}/advertisers"
        },
        "list": {
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.get",
          "description": "Gets one advertiser by ID.",
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "flatPath": "userprofiles/{profileId}/advertisers/{id}"
        },
        "insert": {
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Inserts a new advertiser.",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "httpMethod": "POST",
          "id": "dfareporting.advertisers.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/advertisers"
        }
      }
    },
    "directorySites": {
      "methods": {
        "list": {
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/directorySites",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{profileId}/directorySites/{id}",
          "description": "Gets one directory site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/directorySites/{id}"
        },
        "insert": {
          "description": "Inserts a new directory site.",
          "flatPath": "userprofiles/{profileId}/directorySites",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/directorySites",
          "id": "dfareporting.directorySites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "description": "Retrieves a list of cities, possibly filtered.",
          "path": "userprofiles/{profileId}/cities",
          "id": "dfareporting.cities.list",
          "flatPath": "userprofiles/{profileId}/cities",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.regions.list",
          "path": "userprofiles/{profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/regions",
          "description": "Retrieves a list of regions."
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID.",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.get"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/countries/{dartId}",
          "description": "Gets one country by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/countries",
          "description": "Retrieves a list of countries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.list",
          "path": "userprofiles/{profileId}/countries",
          "httpMethod": "GET"
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.list",
          "path": "userprofiles/{profileId}/files",
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "description": "Lists files for a user profile."
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.get",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "path": "reports/{reportId}/files/{fileId}"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update",
          "description": "Updates an existing advertiser group."
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserGroups.insert",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/accounts/{id}",
          "id": "dfareporting.accounts.get",
          "description": "Gets one account by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accounts/{id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.list"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/accounts",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.update",
          "path": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account."
        }
      }
    },
    "userRoles": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "id": "dfareporting.userRoles.delete"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "id": "dfareporting.userRoles.get",
          "description": "Gets one user role by ID."
        },
        "insert": {
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/userRoles"
        },
        "list": {
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PUT",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing user role."
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch",
          "httpMethod": "PATCH"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "PATCH"
        },
        "update": {
          "id": "dfareporting.placements.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement.",
          "path": "userprofiles/{profileId}/placements",
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements",
          "path": "userprofiles/{profileId}/placements",
          "description": "Inserts a new placement.",
          "id": "dfareporting.placements.insert",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.list",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placements"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "id": "dfareporting.placements.generatetags",
          "path": "userprofiles/{profileId}/placements/generatetags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements/generatetags"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/placements/{id}",
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{profileId}/placements/{id}",
          "description": "Gets one placement by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "path": "userprofiles/{profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of postal codes.",
          "id": "dfareporting.postalCodes.list",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "httpMethod": "GET",
          "description": "Gets one postal code by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.get",
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/userRolePermissions",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered."
        },
        "get": {
          "id": "dfareporting.userRolePermissions.get",
          "description": "Gets one user role permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "eventTags": {
      "methods": {
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "path": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "path": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PUT"
        },
        "get": {
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.get"
        },
        "patch": {
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/eventTags"
        },
        "list": {
          "id": "dfareporting.eventTags.list",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags",
          "path": "userprofiles/{profileId}/eventTags"
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing event tag.",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "id": "dfareporting.eventTags.delete"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.targetableRemarketingLists.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of platform types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "flatPath": "userprofiles/{profileId}/platformTypes"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get",
          "path": "userprofiles/{profileId}/platformTypes/{id}"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "description": "Retrieves a list of browsers.",
          "httpMethod": "GET",
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/browsers"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "id": "dfareporting.mobileCarriers.get",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID."
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileCarriers",
          "flatPath": "userprofiles/{profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers.",
          "id": "dfareporting.mobileCarriers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "description": "Gets one project by ID.",
          "path": "userprofiles/{profileId}/projects/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "id": "dfareporting.projects.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{profileId}/projects",
          "httpMethod": "GET",
          "id": "dfareporting.projects.list",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch"
        },
        "insert": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity group."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups"
        },
        "get": {
          "description": "Gets one floodlight activity group by ID.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.list"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "flatPath": "userprofiles"
        },
        "get": {
          "description": "Gets one user profile by ID.",
          "path": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.get",
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/languages",
          "description": "Retrieves a list of languages."
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "description": "Gets one order document by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orderDocuments.get"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.orderDocuments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments"
        }
      }
    },
    "campaigns": {
      "methods": {
        "patch": {
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "update": {
          "path": "userprofiles/{profileId}/campaigns",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.update",
          "description": "Updates an existing campaign.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.get",
          "description": "Gets one campaign by ID.",
          "path": "userprofiles/{profileId}/campaigns/{id}",
          "flatPath": "userprofiles/{profileId}/campaigns/{id}"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.list"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{profileId}/creativeFields"
        },
        "get": {
          "description": "Gets one creative field by ID.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFields.patch"
        },
        "insert": {
          "description": "Inserts a new creative field.",
          "httpMethod": "POST",
          "id": "dfareporting.creativeFields.insert",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.delete",
          "description": "Deletes an existing creative field."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}",
          "id": "dfareporting.subaccounts.get",
          "description": "Gets one subaccount by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.list"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.update",
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.patch"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.subaccounts.insert",
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new subaccount.",
          "flatPath": "userprofiles/{profileId}/subaccounts"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "id": "dfareporting.targetingTemplates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}",
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "id": "dfareporting.targetingTemplates.get",
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID."
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "id": "dfareporting.targetingTemplates.patch",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/targetingTemplates"
        },
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new targeting template.",
          "httpMethod": "POST"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share."
        },
        "get": {
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get",
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.get",
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID.",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}"
        },
        "update": {
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.list",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered."
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics."
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets the account's active ad summary by account ID.",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "description": "Gets one operating system version by ID."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "description": "Retrieves a list of operating system versions.",
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "path": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging."
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}",
          "id": "dfareporting.creativeGroups.get",
          "httpMethod": "GET",
          "description": "Gets one creative group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups/{id}"
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "path": "userprofiles/{profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "httpMethod": "PATCH"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "delete": {
          "id": "dfareporting.creativeFieldValues.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.list"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "id": "dfareporting.creativeFieldValues.insert",
          "httpMethod": "POST"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field value by ID."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update",
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues"
        },
        "patch": {
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.patch",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH"
        }
      }
    },
    "reports": {
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "supportsMediaDownload": true,
              "id": "dfareporting.reports.files.get",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
            },
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            }
          }
        }
      },
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete"
        },
        "list": {
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "id": "dfareporting.reports.update",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates an existing report. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.patch"
        },
        "run": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Runs a report."
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Creates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.insert",
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "id": "dfareporting.inventoryItems.get",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "httpMethod": "GET",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "id": "dfareporting.inventoryItems.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging."
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "description": "Inserts a new creative asset.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity."
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "description": "Inserts a new floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "id": "dfareporting.floodlightActivities.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity by ID.",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "description": "Deletes an existing floodlight activity.",
          "id": "dfareporting.floodlightActivities.delete"
        },
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "GET"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/mobileApps",
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "id": "dfareporting.mobileApps.list",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "id": "dfareporting.mobileApps.get",
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile app by ID."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/changeLogs",
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "id": "dfareporting.changeLogs.list",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/changeLogs/{id}",
          "id": "dfareporting.changeLogs.get",
          "description": "Gets one change log by ID.",
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}",
          "httpMethod": "GET"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions."
        },
        "batchinsert": {
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions.",
          "id": "dfareporting.conversions.batchinsert"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "update": {
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "description": "Updates an existing landing page.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.update"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.get",
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "list": {
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert",
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates an existing placement group.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update",
          "flatPath": "userprofiles/{profileId}/placementGroups"
        },
        "patch": {
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.patch",
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "PATCH"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID.",
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.list",
          "httpMethod": "GET"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "id": "dfareporting.placementStrategies.delete",
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.list"
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "description": "Gets one placement strategy by ID.",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement strategy."
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PUT"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/metros",
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{profileId}/metros",
          "id": "dfareporting.metros.list",
          "httpMethod": "GET"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "description": "Gets one account permission group by ID."
        },
        "list": {
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.list",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountPermissionGroups"
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "id": "dfareporting.orders.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging."
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "description": "Gets one order by ID.",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "id": "dfareporting.orders.get"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountPermissions/{id}",
          "description": "Gets one account permission by ID.",
          "id": "dfareporting.accountPermissions.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permissions.",
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{profileId}/accountPermissions",
          "path": "userprofiles/{profileId}/accountPermissions",
          "httpMethod": "GET"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{profileId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{profileId}/sites"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one site by ID.",
          "id": "dfareporting.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sites/{id}",
          "path": "userprofiles/{profileId}/sites/{id}"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.sites.insert",
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.sites.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site.",
          "path": "userprofiles/{profileId}/sites",
          "flatPath": "userprofiles/{profileId}/sites"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "id": "dfareporting.dynamicTargetingKeys.delete"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.list",
          "description": "Retrieves a list of dynamic targeting keys."
        },
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}",
          "description": "Gets one video format by ID.",
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/videoFormats",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/videoFormats",
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "list": {
          "id": "dfareporting.remarketingLists.list",
          "path": "userprofiles/{profileId}/remarketingLists",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.insert",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "path": "userprofiles/{profileId}/remarketingLists"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list. This method supports patch semantics."
        },
        "update": {
          "path": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingLists.update",
          "description": "Updates an existing remarketing list."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.remarketingLists.get",
          "path": "userprofiles/{profileId}/remarketingLists/{id}"
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/ads",
          "description": "Inserts a new ad."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad.",
          "id": "dfareporting.ads.update",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads",
          "httpMethod": "PUT"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "get": {
          "description": "Gets one ad by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/ads/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{profileId}/ads/{id}"
        },
        "list": {
          "path": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/ads"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "description": "Gets one operating system by DART ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "id": "dfareporting.operatingSystems.get",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/operatingSystems",
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems."
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "description": "Gets one account user profile by ID.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "id": "dfareporting.accountUserProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update",
          "description": "Updates an existing account user profile.",
          "path": "userprofiles/{profileId}/accountUserProfiles"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.accountUserProfiles.patch",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/accountUserProfiles"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "description": "Inserts a new account user profile.",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "POST"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "id": "dfareporting.contentCategories.get"
        },
        "insert": {
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Inserts a new content category.",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.contentCategories.insert"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PATCH",
          "id": "dfareporting.contentCategories.patch",
          "description": "Updates an existing content category. This method supports patch semantics."
        },
        "list": {
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.list"
        },
        "delete": {
          "id": "dfareporting.contentCategories.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Deletes an existing content category."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PUT",
          "description": "Updates an existing content category.",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.update"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get",
          "flatPath": "userprofiles/{profileId}/creatives/{id}",
          "description": "Gets one creative by ID."
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.creatives.update",
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics."
        },
        "list": {
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creatives",
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.list"
        },
        "insert": {
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "POST"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "description": "Gets one size by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/sizes/{id}",
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.get"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sizes",
          "id": "dfareporting.sizes.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/sizes",
          "description": "Inserts a new size."
        },
        "list": {
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/sizes",
          "path": "userprofiles/{profileId}/sizes",
          "id": "dfareporting.sizes.list"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "id": "dfareporting.connectionTypes.list",
          "flatPath": "userprofiles/{profileId}/connectionTypes",
          "path": "userprofiles/{profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of connection types.",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google",
  "batchPath": "batch",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v3.5/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  }
}
