{
  "version_module": true,
  "description": "",
  "canonicalName": "Google Analytics Admin",
  "revision": "20230228",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "version": "v1beta",
  "ownerName": "Google",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "id": "analyticsadmin:v1beta",
  "batchPath": "batch",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "resources": {
    "properties": {
      "methods": {
        "getDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1beta/{+name}"
        },
        "create": {
          "httpMethod": "POST",
          "flatPath": "v1beta/properties",
          "path": "v1beta/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create"
        },
        "get": {
          "description": "Lookup for a single \"GA4\" Property.",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1beta/properties",
          "httpMethod": "GET"
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "httpMethod": "PATCH",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateDataRetentionSettings"
        },
        "acknowledgeUserDataCollection": {
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection"
        },
        "delete": {
          "path": "v1beta/{+name}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE",
          "flatPath": "v1beta/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete"
        },
        "patch": {
          "flatPath": "v1beta/properties/{propertiesId}",
          "path": "v1beta/{+name}",
          "description": "Updates a property.",
          "id": "analyticsadmin.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH"
        }
      },
      "resources": {
        "dataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                },
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1beta/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret."
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret."
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "PATCH",
                  "path": "v1beta/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "description": "Updates a measurement protocol secret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "get": {
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get"
                }
              }
            }
          },
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.list",
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/dataStreams"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "path": "v1beta/{+parent}/dataStreams",
              "description": "Creates a DataStream.",
              "id": "analyticsadmin.properties.dataStreams.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.get",
              "description": "Lookup for a single DataStream.",
              "httpMethod": "GET",
              "path": "v1beta/{+name}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a DataStream on a property.",
              "id": "analyticsadmin.properties.dataStreams.delete"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a FirebaseLink on a property",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}"
            },
            "create": {
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "path": "v1beta/{+parent}/firebaseLinks"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "path": "v1beta/{+parent}/firebaseLinks"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "path": "v1beta/{+name}"
            },
            "patch": {
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "description": "Creates a GoogleAdsLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/googleAdsLinks"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists GoogleAdsLinks on a property."
            }
          }
        },
        "customDimensions": {
          "methods": {
            "archive": {
              "httpMethod": "POST",
              "description": "Archives a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}:archive",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            },
            "list": {
              "path": "v1beta/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "path": "v1beta/{+name}"
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "path": "v1beta/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.create"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "description": "Creates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Deletes a conversion event in a property.",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list"
            },
            "get": {
              "id": "analyticsadmin.properties.conversionEvents.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Retrieve a single conversion event.",
              "httpMethod": "GET"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "httpMethod": "POST",
              "description": "Archives a CustomMetric on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1beta/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomMetric on a property.",
              "httpMethod": "PATCH",
              "path": "v1beta/{+name}"
            },
            "list": {
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "httpMethod": "GET",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1beta/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/customMetrics",
              "description": "Creates a CustomMetric.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "path": "v1beta/accountSummaries",
          "flatPath": "v1beta/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "id": "analyticsadmin.accounts.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1beta/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings"
        },
        "patch": {
          "description": "Updates an account.",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH",
          "flatPath": "v1beta/accounts/{accountsId}"
        },
        "searchChangeHistoryEvents": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters.",
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "v1beta/accounts",
          "id": "analyticsadmin.accounts.list",
          "httpMethod": "GET",
          "path": "v1beta/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "get": {
          "flatPath": "v1beta/accounts/{accountsId}",
          "description": "Lookup for a single Account.",
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get"
        }
      }
    }
  },
  "name": "analyticsadmin",
  "servicePath": "",
  "title": "Google Analytics Admin API",
  "basePath": "",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "baseUrl": "https://analyticsadmin.googleapis.com/"
}
