{
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "name": "analyticsadmin",
  "protocol": "rest",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "resources": {
    "accounts": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "v1beta/accounts",
          "path": "v1beta/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "id": "analyticsadmin.accounts.list"
        },
        "searchChangeHistoryEvents": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "httpMethod": "POST",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters."
        },
        "getDataSharingSettings": {
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "path": "v1beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings"
        },
        "provisionAccountTicket": {
          "path": "v1beta/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "delete": {
          "id": "analyticsadmin.accounts.delete",
          "path": "v1beta/{+name}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/accounts/{accountsId}"
        },
        "patch": {
          "description": "Updates an account.",
          "httpMethod": "PATCH",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "description": "Lookup for a single Account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accountSummaries.list",
          "flatPath": "v1beta/accountSummaries",
          "path": "v1beta/accountSummaries"
        }
      }
    },
    "properties": {
      "methods": {
        "create": {
          "id": "analyticsadmin.properties.create",
          "path": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1beta/properties",
          "description": "Creates an \"GA4\" property with the specified location and attributes."
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not a GA[...]",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.delete",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "httpMethod": "GET",
          "path": "v1beta/properties",
          "description": "Returns child Properties under the specified parent Account. Only \"GA4\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "flatPath": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "acknowledgeUserDataCollection": {
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getDataRetentionSettings": {
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns the singleton data retention settings for this property."
        },
        "get": {
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Lookup for a single \"GA4\" Property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.patch",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "path": "v1beta/{+name}",
          "description": "Updates a property."
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        }
      },
      "resources": {
        "customDimensions": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "path": "v1beta/{+parent}/customDimensions",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Lookup for a single CustomDimension.",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.get"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "description": "Creates a CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create"
            },
            "patch": {
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Updates a CustomDimension on a property."
            },
            "archive": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "path": "v1beta/{+name}:archive",
              "description": "Archives a CustomDimension on a property."
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.dataStreams.patch"
            },
            "delete": {
              "description": "Deletes a DataStream on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "path": "v1beta/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "description": "Creates a DataStream.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams"
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "description": "Lookup for a single DataStream."
            },
            "list": {
              "id": "analyticsadmin.properties.dataStreams.list",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "path": "v1beta/{+parent}/dataStreams",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DataStreams on a property."
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "get": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single \"GA4\" MeasurementProtocolSecret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get"
                },
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "httpMethod": "DELETE",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "list": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "create": {
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                },
                "patch": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "description": "Updates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "httpMethod": "POST",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}:archive"
            },
            "create": {
              "description": "Creates a CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.create",
              "path": "v1beta/{+parent}/customMetrics",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomMetric on a property.",
              "id": "analyticsadmin.properties.customMetrics.patch"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1beta/{+parent}/customMetrics",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.get",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a GoogleAdsLink on a property",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Deletes a GoogleAdsLink on a property",
              "httpMethod": "DELETE"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a conversion event with the specified attributes.",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/conversionEvents"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "description": "Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "delete": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a conversion event in a property.",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "path": "v1beta/{+name}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Retrieve a single conversion event.",
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "path": "v1beta/{+name}"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "httpMethod": "DELETE",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/firebaseLinks"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1beta/{+parent}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks"
            }
          }
        }
      }
    }
  },
  "version": "v1beta",
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "kind": "discovery#restDescription",
  "title": "Google Analytics Admin API",
  "batchPath": "batch",
  "id": "analyticsadmin:v1beta",
  "version_module": true,
  "servicePath": "",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "revision": "20230228",
  "ownerDomain": "google.com",
  "canonicalName": "Google Analytics Admin",
  "description": "",
  "basePath": ""
}
