{
  "name": "script",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "discoveryVersion": "v1",
  "rootUrl": "https://script.googleapis.com/",
  "servicePath": "",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://script.mtls.googleapis.com/",
  "ownerName": "Google",
  "description": "Manages and executes Google Apps Script projects. ",
  "basePath": "",
  "batchPath": "batch",
  "canonicalName": "Script",
  "title": "Apps Script API",
  "revision": "20230219",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, edit, create, and delete all your Google Docs documents"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        }
      }
    }
  },
  "id": "script:v1",
  "version": "v1",
  "resources": {
    "projects": {
      "resources": {
        "deployments": {
          "methods": {
            "delete": {
              "description": "Deletes a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "DELETE",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.delete",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ]
            },
            "list": {
              "id": "script.projects.deployments.list",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "description": "Lists the deployments of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "path": "v1/projects/{scriptId}/deployments",
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1/projects/{scriptId}/deployments",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "description": "Creates a deployment of an Apps Script project.",
              "id": "script.projects.deployments.create",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.get",
              "description": "Gets a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ]
            },
            "update": {
              "httpMethod": "PUT",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "description": "Updates a deployment of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.update"
            }
          }
        },
        "versions": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "description": "Gets a version of a script project.",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "id": "script.projects.versions.get"
            },
            "create": {
              "flatPath": "v1/projects/{scriptId}/versions",
              "path": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.create",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "description": "Creates a new immutable version using the current code, with a unique version number.",
              "httpMethod": "POST"
            },
            "list": {
              "path": "v1/projects/{scriptId}/versions",
              "httpMethod": "GET",
              "description": "List the versions of a script project.",
              "flatPath": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.list",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ]
            }
          }
        }
      },
      "methods": {
        "getMetrics": {
          "id": "script.projects.getMetrics",
          "path": "v1/projects/{scriptId}/metrics",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "description": "Get metrics data for scripts, such as number of executions and active users.",
          "flatPath": "v1/projects/{scriptId}/metrics"
        },
        "create": {
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "httpMethod": "POST",
          "flatPath": "v1/projects",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "id": "script.projects.create",
          "path": "v1/projects"
        },
        "getContent": {
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "id": "script.projects.getContent",
          "path": "v1/projects/{scriptId}/content",
          "description": "Gets the content of the script project, including the code source and metadata for each script file.",
          "flatPath": "v1/projects/{scriptId}/content",
          "httpMethod": "GET"
        },
        "updateContent": {
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "httpMethod": "PUT",
          "path": "v1/projects/{scriptId}/content",
          "id": "script.projects.updateContent",
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.",
          "flatPath": "v1/projects/{scriptId}/content"
        },
        "get": {
          "description": "Gets a script project's metadata.",
          "path": "v1/projects/{scriptId}",
          "id": "script.projects.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "flatPath": "v1/projects/{scriptId}"
        }
      }
    },
    "processes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "id": "script.processes.list",
          "flatPath": "v1/processes",
          "path": "v1/processes",
          "httpMethod": "GET",
          "description": "List information about processes made by or on behalf of a user, such as process type and current status."
        },
        "listScriptProcesses": {
          "description": "List information about a script's executed processes, such as process type and current status.",
          "id": "script.processes.listScriptProcesses",
          "flatPath": "v1/processes:listScriptProcesses",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "path": "v1/processes:listScriptProcesses",
          "httpMethod": "GET"
        }
      }
    },
    "scripts": {
      "methods": {
        "run": {
          "path": "v1/scripts/{scriptId}:run",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "description": "Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in [...]",
          "flatPath": "v1/scripts/{scriptId}:run",
          "id": "script.scripts.run",
          "httpMethod": "POST"
        }
      }
    }
  },
  "baseUrl": "https://script.googleapis.com/",
  "kind": "discovery#restDescription"
}
