{
  "servicePath": "",
  "baseUrl": "https://script.googleapis.com/",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "rootUrl": "https://script.googleapis.com/",
  "resources": {
    "scripts": {
      "methods": {
        "run": {
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "description": "Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in [...]",
          "flatPath": "v1/scripts/{scriptId}:run",
          "httpMethod": "POST",
          "id": "script.scripts.run",
          "path": "v1/scripts/{scriptId}:run"
        }
      }
    },
    "projects": {
      "methods": {
        "create": {
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "flatPath": "v1/projects",
          "path": "v1/projects",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "httpMethod": "POST",
          "id": "script.projects.create"
        },
        "getContent": {
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "id": "script.projects.getContent",
          "path": "v1/projects/{scriptId}/content",
          "flatPath": "v1/projects/{scriptId}/content",
          "httpMethod": "GET",
          "description": "Gets the content of the script project, including the code source and metadata for each script file."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a script project's metadata.",
          "path": "v1/projects/{scriptId}",
          "flatPath": "v1/projects/{scriptId}",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "id": "script.projects.get"
        },
        "updateContent": {
          "flatPath": "v1/projects/{scriptId}/content",
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.",
          "id": "script.projects.updateContent",
          "httpMethod": "PUT",
          "path": "v1/projects/{scriptId}/content",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ]
        },
        "getMetrics": {
          "description": "Get metrics data for scripts, such as number of executions and active users.",
          "path": "v1/projects/{scriptId}/metrics",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "id": "script.projects.getMetrics",
          "httpMethod": "GET",
          "flatPath": "v1/projects/{scriptId}/metrics"
        }
      },
      "resources": {
        "versions": {
          "methods": {
            "create": {
              "id": "script.projects.versions.create",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "flatPath": "v1/projects/{scriptId}/versions",
              "httpMethod": "POST",
              "path": "v1/projects/{scriptId}/versions",
              "description": "Creates a new immutable version using the current code, with a unique version number."
            },
            "get": {
              "id": "script.projects.versions.get",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "httpMethod": "GET",
              "description": "Gets a version of a script project.",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}"
            },
            "list": {
              "description": "List the versions of a script project.",
              "httpMethod": "GET",
              "id": "script.projects.versions.list",
              "path": "v1/projects/{scriptId}/versions",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "flatPath": "v1/projects/{scriptId}/versions"
            }
          }
        },
        "deployments": {
          "methods": {
            "list": {
              "description": "Lists the deployments of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments",
              "id": "script.projects.deployments.list",
              "path": "v1/projects/{scriptId}/deployments",
              "httpMethod": "GET"
            },
            "get": {
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Gets a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "id": "script.projects.deployments.get",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "GET"
            },
            "update": {
              "description": "Updates a deployment of an Apps Script project.",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.update",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "create": {
              "flatPath": "v1/projects/{scriptId}/deployments",
              "description": "Creates a deployment of an Apps Script project.",
              "path": "v1/projects/{scriptId}/deployments",
              "httpMethod": "POST",
              "id": "script.projects.deployments.create",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ]
            },
            "delete": {
              "id": "script.projects.deployments.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Deletes a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            }
          }
        }
      }
    },
    "processes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "List information about processes made by or on behalf of a user, such as process type and current status.",
          "id": "script.processes.list",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "path": "v1/processes",
          "flatPath": "v1/processes"
        },
        "listScriptProcesses": {
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "path": "v1/processes:listScriptProcesses",
          "description": "List information about a script's executed processes, such as process type and current status.",
          "flatPath": "v1/processes:listScriptProcesses",
          "id": "script.processes.listScriptProcesses",
          "httpMethod": "GET"
        }
      }
    }
  },
  "basePath": "",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "version": "v1",
  "title": "Apps Script API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, edit, create, and delete all your Google Docs documents"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        }
      }
    }
  },
  "ownerName": "Google",
  "protocol": "rest",
  "name": "script",
  "kind": "discovery#restDescription",
  "id": "script:v1",
  "description": "Manages and executes Google Apps Script projects. ",
  "revision": "20230219",
  "canonicalName": "Script",
  "mtlsRootUrl": "https://script.mtls.googleapis.com/"
}
