{
  "id": "script:v1",
  "mtlsRootUrl": "https://script.mtls.googleapis.com/",
  "revision": "20230219",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "description": "Manages and executes Google Apps Script projects. ",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "name": "script",
  "title": "Apps Script API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, edit, create, and delete all your Google Docs documents"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        }
      }
    }
  },
  "baseUrl": "https://script.googleapis.com/",
  "basePath": "",
  "ownerDomain": "google.com",
  "rootUrl": "https://script.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Script",
  "resources": {
    "projects": {
      "resources": {
        "deployments": {
          "methods": {
            "update": {
              "httpMethod": "PUT",
              "id": "script.projects.deployments.update",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Updates a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "list": {
              "id": "script.projects.deployments.list",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists the deployments of an Apps Script project.",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "path": "v1/projects/{scriptId}/deployments"
            },
            "delete": {
              "description": "Deletes a deployment of an Apps Script project.",
              "id": "script.projects.deployments.delete",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "create": {
              "id": "script.projects.deployments.create",
              "flatPath": "v1/projects/{scriptId}/deployments",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "path": "v1/projects/{scriptId}/deployments",
              "description": "Creates a deployment of an Apps Script project.",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "GET",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "id": "script.projects.deployments.get",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "description": "Gets a deployment of an Apps Script project."
            }
          }
        },
        "versions": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.list",
              "path": "v1/projects/{scriptId}/versions",
              "description": "List the versions of a script project."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "description": "Gets a version of a script project.",
              "id": "script.projects.versions.get",
              "httpMethod": "GET",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new immutable version using the current code, with a unique version number.",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "flatPath": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.create",
              "path": "v1/projects/{scriptId}/versions"
            }
          }
        }
      },
      "methods": {
        "updateContent": {
          "id": "script.projects.updateContent",
          "path": "v1/projects/{scriptId}/content",
          "flatPath": "v1/projects/{scriptId}/content",
          "httpMethod": "PUT",
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ]
        },
        "create": {
          "flatPath": "v1/projects",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "id": "script.projects.create",
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "path": "v1/projects"
        },
        "getMetrics": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "path": "v1/projects/{scriptId}/metrics",
          "flatPath": "v1/projects/{scriptId}/metrics",
          "description": "Get metrics data for scripts, such as number of executions and active users.",
          "id": "script.projects.getMetrics"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "path": "v1/projects/{scriptId}",
          "httpMethod": "GET",
          "flatPath": "v1/projects/{scriptId}",
          "description": "Gets a script project's metadata.",
          "id": "script.projects.get"
        },
        "getContent": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "path": "v1/projects/{scriptId}/content",
          "description": "Gets the content of the script project, including the code source and metadata for each script file.",
          "id": "script.projects.getContent",
          "flatPath": "v1/projects/{scriptId}/content"
        }
      }
    },
    "processes": {
      "methods": {
        "listScriptProcesses": {
          "path": "v1/processes:listScriptProcesses",
          "httpMethod": "GET",
          "flatPath": "v1/processes:listScriptProcesses",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "description": "List information about a script's executed processes, such as process type and current status.",
          "id": "script.processes.listScriptProcesses"
        },
        "list": {
          "id": "script.processes.list",
          "flatPath": "v1/processes",
          "description": "List information about processes made by or on behalf of a user, such as process type and current status.",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "httpMethod": "GET",
          "path": "v1/processes"
        }
      }
    },
    "scripts": {
      "methods": {
        "run": {
          "httpMethod": "POST",
          "flatPath": "v1/scripts/{scriptId}:run",
          "description": "Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in [...]",
          "path": "v1/scripts/{scriptId}:run",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "id": "script.scripts.run"
        }
      }
    }
  },
  "version": "v1",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "servicePath": ""
}
