{
  "ownerName": "Google",
  "id": "games:v1",
  "protocol": "rest",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "resources": {
    "achievements": {
      "methods": {
        "updateMultiple": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Updates multiple achievements for the currently authenticated player.",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple",
          "path": "games/v1/achievements/updateMultiple"
        },
        "setStepsAtLeast": {
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "id": "games.achievements.setStepsAtLeast",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        },
        "reveal": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/reveal",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST",
          "id": "games.achievements.reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player."
        },
        "increment": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "path": "games/v1/achievements/{achievementId}/increment",
          "httpMethod": "POST",
          "id": "games.achievements.increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player."
        },
        "list": {
          "path": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "id": "games.achievements.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/achievements"
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "id": "games.achievements.unlock",
          "httpMethod": "POST",
          "path": "games/v1/achievements/{achievementId}/unlock"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "id": "games.leaderboards.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID."
        },
        "list": {
          "id": "games.leaderboards.list",
          "path": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the leaderboard metadata for your application.",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "flatPath": "games/v1/revisions/check",
          "path": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date."
        }
      }
    },
    "applications": {
      "methods": {
        "getEndPoint": {
          "flatPath": "games/v1/applications/getEndPoint",
          "description": "Returns a URL for the requested end point type.",
          "id": "games.applications.getEndPoint",
          "httpMethod": "POST",
          "path": "games/v1/applications/getEndPoint",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "played": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/played",
          "flatPath": "games/v1/applications/played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "id": "games.applications.played"
        },
        "verify": {
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "id": "games.applications.verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/{applicationId}/verify"
        },
        "get": {
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "flatPath": "games/v1/applications/{applicationId}",
          "id": "games.applications.get",
          "path": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "id": "games.scores.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listWindow": {
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "id": "games.scores.listWindow",
          "httpMethod": "GET"
        },
        "submitMultiple": {
          "path": "games/v1/leaderboards/scores",
          "httpMethod": "POST",
          "flatPath": "games/v1/leaderboards/scores",
          "id": "games.scores.submitMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Submits multiple scores to leaderboards."
        },
        "list": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list",
          "httpMethod": "GET",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submit": {
          "httpMethod": "POST",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "id": "games.scores.submit",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "players": {
      "methods": {
        "getScopedPlayerIds": {
          "id": "games.players.getScopedPlayerIds",
          "path": "games/v1/players/me/scopedIds",
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "flatPath": "games/v1/players/me/scopedIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "path": "games/v1/players/{playerId}",
          "flatPath": "games/v1/players/{playerId}",
          "id": "games.players.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "id": "games.players.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Get the collection of players for the currently authenticated user.",
          "flatPath": "games/v1/players/me/players/{collection}",
          "path": "games/v1/players/me/players/{collection}",
          "httpMethod": "GET"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "flatPath": "games/v1/stats",
          "path": "games/v1/stats",
          "id": "games.stats.get",
          "httpMethod": "GET",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.metagame.listCategoriesByPlayer",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}"
        },
        "getMetagameConfig": {
          "description": "Return the metagame configuration data for the calling application.",
          "flatPath": "games/v1/metagameConfig",
          "id": "games.metagame.getMetagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/metagameConfig"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "description": "Lists all the achievement definitions for your application.",
          "path": "games/v1/achievements",
          "httpMethod": "GET",
          "id": "games.achievementDefinitions.list",
          "flatPath": "games/v1/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "id": "games.snapshots.get",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/snapshots/{snapshotId}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/snapshots",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID."
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "id": "games.events.record",
          "flatPath": "games/v1/events",
          "httpMethod": "POST",
          "path": "games/v1/events"
        },
        "listDefinitions": {
          "httpMethod": "GET",
          "path": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/eventDefinitions",
          "id": "games.events.listDefinitions",
          "description": "Returns a list of the event definitions in this application."
        },
        "listByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.listByPlayer",
          "flatPath": "games/v1/events",
          "path": "games/v1/events",
          "httpMethod": "GET",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user."
        }
      }
    }
  },
  "servicePath": "",
  "kind": "discovery#restDescription",
  "revision": "20230221",
  "title": "Google Play Game Services",
  "canonicalName": "Games",
  "batchPath": "batch",
  "rootUrl": "https://games.googleapis.com/",
  "name": "games",
  "documentationLink": "https://developers.google.com/games/",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "basePath": "",
  "ownerDomain": "google.com",
  "version": "v1",
  "baseUrl": "https://games.googleapis.com/"
}
