{
  "fullyEncodeReservedExpansion": true,
  "version": "v2",
  "discoveryVersion": "v1",
  "servicePath": "",
  "ownerName": "Google",
  "description": "Retrieves your YouTube Analytics data.",
  "resources": {
    "groups": {
      "methods": {
        "update": {
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "httpMethod": "PUT",
          "id": "youtubeAnalytics.groups.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Modifies a group. For example, you could change a group's title."
        },
        "delete": {
          "id": "youtubeAnalytics.groups.delete",
          "path": "v2/groups",
          "flatPath": "v2/groups",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Deletes a group."
        },
        "list": {
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groups.list",
          "path": "v2/groups"
        },
        "insert": {
          "id": "youtubeAnalytics.groups.insert",
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Creates a group.",
          "httpMethod": "POST"
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "flatPath": "v2/reports",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/reports",
          "description": "Retrieve your YouTube Analytics reports.",
          "id": "youtubeAnalytics.reports.query"
        }
      }
    },
    "groupItems": {
      "methods": {
        "insert": {
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "httpMethod": "POST",
          "id": "youtubeAnalytics.groupItems.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Creates a group item."
        },
        "delete": {
          "path": "v2/groupItems",
          "httpMethod": "DELETE",
          "flatPath": "v2/groupItems",
          "description": "Removes an item from a group.",
          "id": "youtubeAnalytics.groupItems.delete",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "list": {
          "flatPath": "v2/groupItems",
          "description": "Returns a collection of group items that match the API request parameters.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.list",
          "httpMethod": "GET"
        }
      }
    }
  },
  "version_module": true,
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "name": "youtubeAnalytics",
  "id": "youtubeAnalytics:v2",
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "basePath": "",
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "batchPath": "batch",
  "revision": "20230226",
  "canonicalName": "YouTube Analytics",
  "title": "YouTube Analytics API",
  "protocol": "rest"
}
