{
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "basePath": "/dfareporting/v4/",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        }
      }
    }
  },
  "name": "dfareporting",
  "version": "v4",
  "id": "dfareporting:v4",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "servicePath": "dfareporting/v4/",
  "canonicalName": "Dfareporting",
  "discoveryVersion": "v1",
  "resources": {
    "placementStrategies": {
      "methods": {
        "patch": {
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.patch"
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}"
        },
        "delete": {
          "id": "dfareporting.placementStrategies.delete",
          "description": "Deletes an existing placement strategy.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "path": "userprofiles/{profileId}/placementStrategies/{id}"
        },
        "list": {
          "id": "dfareporting.placementStrategies.list",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies"
        },
        "update": {
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "httpMethod": "PUT"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "id": "dfareporting.contentCategories.list",
          "path": "userprofiles/{profileId}/contentCategories",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Inserts a new content category."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one content category by ID.",
          "id": "dfareporting.contentCategories.get",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/contentCategories/{id}"
        },
        "delete": {
          "description": "Deletes an existing content category.",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.contentCategories.delete",
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.update",
          "httpMethod": "PUT",
          "description": "Updates an existing content category.",
          "flatPath": "userprofiles/{profileId}/contentCategories"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.billingProfiles.get",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{id}",
          "path": "userprofiles/{profileId}/billingProfiles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one billing profile by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/billingProfiles"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing billing profile.",
          "path": "userprofiles/{profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update",
          "flatPath": "userprofiles/{profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "id": "dfareporting.operatingSystemVersions.get",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}"
        },
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating system versions."
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/floodlightActivityGroups"
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "httpMethod": "PUT"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.get",
          "description": "Gets one floodlight activity group by ID.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}"
        },
        "insert": {
          "id": "dfareporting.floodlightActivityGroups.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountPermissions"
        },
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "path": "userprofiles/{profileId}/accountPermissions/{id}",
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "update": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserGroups.update",
          "flatPath": "userprofiles/{profileId}/advertiserGroups"
        },
        "patch": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.patch",
          "description": "Updates an existing advertiser group. This method supports patch semantics."
        },
        "list": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging."
        },
        "delete": {
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete"
        },
        "get": {
          "description": "Gets one advertiser group by ID.",
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}"
        },
        "insert": {
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "description": "Gets one connection type by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.connectionTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/connectionTypes/{id}"
        },
        "list": {
          "id": "dfareporting.connectionTypes.list",
          "path": "userprofiles/{profileId}/connectionTypes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/connectionTypes",
          "description": "Retrieves a list of connection types."
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/remarketingLists"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.insert",
          "description": "Inserts a new remarketing list.",
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/remarketingLists"
        },
        "update": {
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingLists.update",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists/{id}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID."
        }
      }
    },
    "ads": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.patch",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.list"
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/ads",
          "description": "Inserts a new ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "get": {
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/ads/{id}",
          "flatPath": "userprofiles/{profileId}/ads/{id}",
          "id": "dfareporting.ads.get",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads",
          "path": "userprofiles/{profileId}/ads",
          "description": "Updates an existing ad.",
          "id": "dfareporting.ads.update",
          "httpMethod": "PUT"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list",
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID.",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.list",
          "description": "Retrieves a list of change logs. This method supports paging."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/changeLogs/{id}",
          "id": "dfareporting.changeLogs.get",
          "description": "Gets one change log by ID.",
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}",
          "httpMethod": "GET"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers.",
          "path": "userprofiles/{profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "id": "dfareporting.mobileCarriers.get",
          "description": "Gets one mobile carrier by ID.",
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site.",
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{profileId}/directorySites"
        },
        "list": {
          "path": "userprofiles/{profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/directorySites"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/directorySites/{id}",
          "id": "dfareporting.directorySites.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "description": "Gets one directory site by ID."
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "description": "Gets a list of all supported user role permission groups.",
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "id": "dfareporting.userRolePermissionGroups.get"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/languages",
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of languages."
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list",
          "description": "Retrieves a list of billing assignments.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "id": "dfareporting.billingRates.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "description": "Inserts a new advertiser.",
          "path": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertisers"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.list",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.patch",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/advertisers"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "id": "dfareporting.advertisers.get",
          "flatPath": "userprofiles/{profileId}/advertisers/{id}",
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.get",
          "description": "Gets one project by ID.",
          "path": "userprofiles/{profileId}/projects/{id}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.projects.list",
          "path": "userprofiles/{profileId}/projects",
          "flatPath": "userprofiles/{profileId}/projects",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "httpMethod": "GET"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFields.delete",
          "description": "Deletes an existing creative field."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "description": "Gets one creative field by ID.",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.update"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new creative field.",
          "path": "userprofiles/{profileId}/creativeFields",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "list": {
          "path": "userprofiles/{profileId}/creativeFields",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFields.list"
        }
      }
    },
    "userRoles": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Gets one user role by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.get",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "POST",
          "id": "dfareporting.userRoles.insert",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "description": "Inserts a new user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/userRoles/{id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.update",
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles"
        },
        "list": {
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.get",
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}"
        },
        "list": {
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.list",
          "path": "userprofiles/{profileId}/targetingTemplates"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new targeting template.",
          "id": "dfareporting.targetingTemplates.insert",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.update",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics."
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get",
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.list",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "path": "userprofiles/{profileId}/targetableRemarketingLists"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "description": "Inserts a new creative asset.",
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert",
          "httpMethod": "POST"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "id": "dfareporting.files.get",
          "path": "reports/{reportId}/files/{fileId}",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "list": {
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Lists files for a user profile.",
          "httpMethod": "GET",
          "id": "dfareporting.files.list",
          "flatPath": "userprofiles/{profileId}/files"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserInvoices.list",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity by ID.",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.floodlightActivities.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing floodlight activity.",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.list",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging."
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "generatetag": {
          "description": "Generates a tag for a floodlight activity.",
          "id": "dfareporting.floodlightActivities.generatetag",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/regions",
          "id": "dfareporting.regions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of regions."
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing dynamic targeting key.",
          "id": "dfareporting.dynamicTargetingKeys.delete"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys."
        }
      }
    },
    "campaigns": {
      "methods": {
        "update": {
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns/{id}",
          "id": "dfareporting.campaigns.get",
          "httpMethod": "GET",
          "description": "Gets one campaign by ID.",
          "path": "userprofiles/{profileId}/campaigns/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/campaigns",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging."
        },
        "patch": {
          "id": "dfareporting.campaigns.patch",
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.insert",
          "description": "Inserts a new campaign.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/campaigns"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "id": "dfareporting.browsers.list"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value."
        },
        "delete": {
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFieldValues.delete",
          "description": "Deletes an existing creative field value.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "id": "dfareporting.creativeFieldValues.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.list",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value."
        },
        "get": {
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps.",
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "path": "userprofiles/{profileId}/mobileApps",
          "id": "dfareporting.mobileApps.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "description": "Gets one mobile app by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "httpMethod": "GET"
        }
      }
    },
    "placements": {
      "methods": {
        "update": {
          "id": "dfareporting.placements.update",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements"
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{profileId}/placements",
          "path": "userprofiles/{profileId}/placements"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "path": "userprofiles/{profileId}/placements/generatetags",
          "flatPath": "userprofiles/{profileId}/placements/generatetags",
          "httpMethod": "POST",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placements/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.get",
          "flatPath": "userprofiles/{profileId}/placements/{id}",
          "description": "Gets one placement by ID."
        },
        "insert": {
          "id": "dfareporting.placements.insert",
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "path": "userprofiles/{profileId}/placements",
          "flatPath": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group.",
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.placementGroups.update"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "description": "Gets one placement group by ID.",
          "id": "dfareporting.placementGroups.get",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement group.",
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/cities",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.cities.list",
          "flatPath": "userprofiles/{profileId}/cities",
          "description": "Retrieves a list of cities, possibly filtered."
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.countries.list",
          "flatPath": "userprofiles/{profileId}/countries",
          "description": "Retrieves a list of countries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/countries"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get",
          "description": "Gets one country by ID.",
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/countries/{dartId}"
        }
      }
    },
    "creatives": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.update",
          "path": "userprofiles/{profileId}/creatives",
          "description": "Updates an existing creative.",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/creatives"
        },
        "insert": {
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "id": "dfareporting.creatives.insert",
          "path": "userprofiles/{profileId}/creatives",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creatives/{id}",
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "description": "Gets one creative by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creatives"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/postalCodes",
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.list",
          "description": "Retrieves a list of postal codes."
        },
        "get": {
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "id": "dfareporting.postalCodes.get"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "flatPath": "userprofiles",
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions.",
          "httpMethod": "POST",
          "id": "dfareporting.conversions.batchupdate"
        },
        "batchinsert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Inserts conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "description": "Gets one user role permission by ID.",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "description": "Gets a list of user role permissions, possibly filtered."
        }
      }
    },
    "sizes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/sizes",
          "path": "userprofiles/{profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "description": "Gets one size by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/sizes/{id}",
          "id": "dfareporting.sizes.get"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size.",
          "id": "dfareporting.sizes.insert",
          "path": "userprofiles/{profileId}/sizes"
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one order document by ID.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "id": "dfareporting.orderDocuments.get"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orderDocuments.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments"
        }
      }
    },
    "reports": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports."
        },
        "update": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "id": "dfareporting.reports.update"
        },
        "delete": {
          "id": "dfareporting.reports.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "get": {
          "description": "Retrieves a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "insert": {
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Creates a report.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.patch",
          "description": "Updates an existing report. This method supports patch semantics."
        },
        "run": {
          "httpMethod": "POST",
          "id": "dfareporting.reports.run",
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "id": "dfareporting.reports.compatibleFields.query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "supportsMediaDownload": true,
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.files.get",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET"
            },
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "description": "Lists files for a report.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.get",
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "description": "Gets one creative group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{profileId}/creativeGroups",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PATCH"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{profileId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/creativeGroups"
        },
        "list": {
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeGroups"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "list": {
          "description": "Retrieves a list of landing pages.",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "update": {
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "httpMethod": "PUT"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "description": "Gets one landing page by ID.",
          "id": "dfareporting.advertiserLandingPages.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserLandingPages.insert"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "list": {
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles"
        },
        "get": {
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "id": "dfareporting.accountUserProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account user profile by ID.",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile.",
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account user profile. This method supports patch semantics."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.get",
          "description": "Gets one subaccount by ID.",
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}"
        },
        "insert": {
          "path": "userprofiles/{profileId}/subaccounts",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "id": "dfareporting.subaccounts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "path": "userprofiles/{profileId}/subaccounts"
        },
        "patch": {
          "path": "userprofiles/{profileId}/subaccounts",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging."
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/accounts/{id}",
          "flatPath": "userprofiles/{profileId}/accounts/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accounts.get"
        },
        "list": {
          "id": "dfareporting.accounts.list",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.patch"
        },
        "update": {
          "path": "userprofiles/{profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.update",
          "description": "Updates an existing account.",
          "httpMethod": "PUT"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "description": "Lists available video formats.",
          "flatPath": "userprofiles/{profileId}/videoFormats",
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/videoFormats",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}",
          "description": "Gets one video format by ID.",
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list"
        },
        "patch": {
          "id": "dfareporting.floodlightConfigurations.patch",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "PUT"
        },
        "get": {
          "description": "Gets one floodlight configuration by ID.",
          "id": "dfareporting.floodlightConfigurations.get",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "httpMethod": "GET"
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "description": "Deletes an existing event tag.",
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}"
        },
        "insert": {
          "path": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.insert",
          "httpMethod": "POST",
          "description": "Inserts a new event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID.",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered."
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/eventTags",
          "path": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "flatPath": "userprofiles/{profileId}/eventTags"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/platformTypes",
          "flatPath": "userprofiles/{profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get",
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "description": "Gets one platform type by ID."
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "id": "dfareporting.orders.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.orders.get",
          "description": "Gets one order by ID.",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.inventoryItems.list",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems"
        },
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/operatingSystems",
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "description": "Retrieves a list of operating systems.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.operatingSystems.get",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "description": "Gets one operating system by DART ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "path": "userprofiles/{profileId}/remarketingListShares",
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.remarketingListShares.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list share by remarketing list ID.",
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}"
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "flatPath": "userprofiles/{profileId}/remarketingListShares"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/sites"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/sites",
          "path": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new site.",
          "id": "dfareporting.sites.insert"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/sites/{id}",
          "id": "dfareporting.sites.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one site by ID.",
          "path": "userprofiles/{profileId}/sites/{id}"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{profileId}/sites",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site."
        },
        "list": {
          "path": "userprofiles/{profileId}/sites",
          "flatPath": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.sites.list"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "id": "dfareporting.metros.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/metros",
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{profileId}/metros"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters."
        }
      }
    }
  },
  "revision": "20230210",
  "title": "Campaign Manager 360 API",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "ownerName": "Google",
  "rootUrl": "https://dfareporting.googleapis.com/"
}
