{
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "title": "Campaign Manager 360 API",
  "servicePath": "dfareporting/v4/",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "id": "dfareporting:v4",
  "resources": {
    "regions": {
      "methods": {
        "list": {
          "id": "dfareporting.regions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/regions",
          "description": "Retrieves a list of regions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/regions"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "PUT"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "description": "Retrieves a list of floodlight configurations, possibly filtered."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.get",
          "description": "Gets one floodlight configuration by ID.",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "description": "Retrieves a list of languages.",
          "path": "userprofiles/{profileId}/languages",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "subaccounts": {
      "methods": {
        "list": {
          "id": "dfareporting.subaccounts.list",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/subaccounts"
        },
        "update": {
          "id": "dfareporting.subaccounts.update",
          "path": "userprofiles/{profileId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/subaccounts"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}",
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "id": "dfareporting.subaccounts.get"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.insert",
          "description": "Inserts a new subaccount."
        },
        "patch": {
          "path": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.patch"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert"
        },
        "list": {
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.list"
        },
        "patch": {
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "description": "Gets one account user profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}"
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/accountUserProfiles"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "description": "Gets one floodlight activity group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.get",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}"
        },
        "list": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivityGroups.update",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups"
        },
        "insert": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics."
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "insert": {
          "id": "dfareporting.advertiserLandingPages.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "id": "dfareporting.advertiserLandingPages.get",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one landing page by ID."
        },
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserLandingPages.update",
          "description": "Updates an existing landing page.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "id": "dfareporting.conversions.batchinsert"
        },
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions."
        }
      }
    },
    "reports": {
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "id": "dfareporting.reports.compatibleFields.query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "id": "dfareporting.reports.files.get"
            },
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Lists files for a report."
            }
          }
        }
      },
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID.",
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list",
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.patch",
          "description": "Updates an existing report. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "run": {
          "httpMethod": "POST",
          "description": "Runs a report.",
          "id": "dfareporting.reports.run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "update": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.update"
        },
        "delete": {
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID.",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "description": "Creates a report.",
          "path": "userprofiles/{profileId}/reports"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "httpMethod": "GET",
          "description": "Gets one inventory item by ID.",
          "id": "dfareporting.inventoryItems.get",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "id": "dfareporting.inventoryItems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys."
        },
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "description": "Deletes an existing dynamic targeting key.",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "POST"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of browsers.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/browsers",
          "flatPath": "userprofiles/{profileId}/browsers"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update"
        },
        "patch": {
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.patch",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics."
        },
        "insert": {
          "description": "Inserts a new placement group.",
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.list",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement group by ID.",
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get",
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list share.",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{profileId}/remarketingListShares"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.patch"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "update": {
          "description": "Updates an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFields.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.patch",
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.creativeFields.list",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "get": {
          "description": "Gets one creative field by ID.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeFields/{id}"
        },
        "insert": {
          "path": "userprofiles/{profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "description": "Deletes an existing creative field.",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}"
        }
      }
    },
    "userRoles": {
      "methods": {
        "get": {
          "id": "dfareporting.userRoles.get",
          "description": "Gets one user role by ID.",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Deletes an existing user role."
        },
        "insert": {
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "httpMethod": "POST",
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRoles"
        },
        "patch": {
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.update"
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of event tags, possibly filtered.",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.list"
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "description": "Gets one event tag by ID.",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new event tag.",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "POST",
          "id": "dfareporting.eventTags.insert"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/eventTags",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PUT",
          "description": "Updates an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.update"
        },
        "delete": {
          "description": "Deletes an existing event tag.",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.eventTags.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "path": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "id": "dfareporting.userRolePermissionGroups.list"
        },
        "get": {
          "id": "dfareporting.userRolePermissionGroups.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "description": "Gets one user role permission group by ID."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already."
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging."
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "id": "dfareporting.orders.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one order by ID."
        },
        "list": {
          "id": "dfareporting.orders.list",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{profileId}/metros",
          "description": "Retrieves a list of metros.",
          "flatPath": "userprofiles/{profileId}/metros"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.billingRates.list",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.get",
          "description": "Gets one user profile by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}",
          "flatPath": "userprofiles/{profileId}"
        },
        "list": {
          "description": "Retrieves list of user profiles for a user.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.list",
          "path": "userprofiles"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "flatPath": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "accounts": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accounts",
          "flatPath": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.patch",
          "description": "Updates an existing account. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accounts/{id}",
          "id": "dfareporting.accounts.get",
          "flatPath": "userprofiles/{profileId}/accounts/{id}"
        },
        "update": {
          "path": "userprofiles/{profileId}/accounts",
          "flatPath": "userprofiles/{profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account.",
          "httpMethod": "PUT",
          "id": "dfareporting.accounts.update"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accounts",
          "path": "userprofiles/{profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "update": {
          "description": "Updates an existing billing profile.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/billingProfiles"
        },
        "get": {
          "path": "userprofiles/{profileId}/billingProfiles/{id}",
          "description": "Gets one billing profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.billingProfiles.get",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.billingProfiles.list",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/billingProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/billingProfiles"
        }
      }
    },
    "campaigns": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "insert": {
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "get": {
          "path": "userprofiles/{profileId}/campaigns/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/campaigns/{id}",
          "description": "Gets one campaign by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.get"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.patch"
        },
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "httpMethod": "GET"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one directory site by ID.",
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "id": "dfareporting.directorySites.get",
          "path": "userprofiles/{profileId}/directorySites/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new directory site.",
          "id": "dfareporting.directorySites.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/directorySites",
          "flatPath": "userprofiles/{profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{profileId}/directorySites",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "path": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "id": "dfareporting.files.get"
        },
        "list": {
          "description": "Lists files for a user profile.",
          "id": "dfareporting.files.list",
          "path": "userprofiles/{profileId}/files",
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivities.patch",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivities.list",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "generatetag": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.generatetag",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "httpMethod": "POST"
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.delete",
          "httpMethod": "DELETE"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity.",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivities.update",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "get": {
          "description": "Gets one floodlight activity by ID.",
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity."
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{profileId}/sizes",
          "path": "userprofiles/{profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.sizes.insert",
          "description": "Inserts a new size."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sizes",
          "path": "userprofiles/{profileId}/sizes",
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/sizes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "id": "dfareporting.sizes.get",
          "description": "Gets one size by ID."
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "id": "dfareporting.projects.get",
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "description": "Gets one project by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{id}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/projects",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects",
          "id": "dfareporting.projects.list",
          "httpMethod": "GET"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "update": {
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.remarketingLists.get",
          "path": "userprofiles/{profileId}/remarketingLists/{id}",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch"
        },
        "list": {
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissions.get",
          "description": "Gets one user role permission by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.list",
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "path": "userprofiles/{profileId}/userRolePermissions",
          "flatPath": "userprofiles/{profileId}/userRolePermissions"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/ads",
          "description": "Inserts a new ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one ad by ID.",
          "path": "userprofiles/{profileId}/ads/{id}",
          "flatPath": "userprofiles/{profileId}/ads/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "PATCH",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/ads",
          "path": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad.",
          "httpMethod": "PUT"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "insert": {
          "description": "Inserts a new targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates an existing targeting template.",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.update",
          "flatPath": "userprofiles/{profileId}/targetingTemplates"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "id": "dfareporting.targetingTemplates.get",
          "description": "Gets one targeting template by ID."
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of connection types.",
          "path": "userprofiles/{profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/connectionTypes"
        },
        "get": {
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "description": "Gets one connection type by ID."
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "description": "Gets the account's active ad summary by account ID.",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "id": "dfareporting.advertiserGroups.get",
          "httpMethod": "GET",
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}"
        },
        "insert": {
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert",
          "path": "userprofiles/{profileId}/advertiserGroups"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.advertiserGroups.list"
        },
        "update": {
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update"
        },
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of change logs. This method supports paging.",
          "id": "dfareporting.changeLogs.list",
          "path": "userprofiles/{profileId}/changeLogs",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one change log by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{profileId}/changeLogs/{id}",
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}"
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one order document by ID.",
          "id": "dfareporting.orderDocuments.get",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}"
        },
        "list": {
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "id": "dfareporting.orderDocuments.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "id": "dfareporting.operatingSystems.get",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves a list of operating systems.",
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.list",
          "path": "userprofiles/{profileId}/operatingSystems",
          "httpMethod": "GET"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.list",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "description": "Inserts a new creative field value."
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "description": "Gets one creative field value by ID.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}"
        },
        "patch": {
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "id": "dfareporting.creativeFieldValues.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues"
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "description": "Updates an existing creative field value.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PUT"
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.list",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/creatives",
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creatives"
        },
        "get": {
          "description": "Gets one creative by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "flatPath": "userprofiles/{profileId}/creatives/{id}"
        },
        "patch": {
          "description": "Updates an existing creative. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "description": "Retrieves a list of operating system versions.",
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.list",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "description": "Gets one operating system version by ID.",
          "id": "dfareporting.operatingSystemVersions.get"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "path": "userprofiles/{profileId}/mobileApps",
          "id": "dfareporting.mobileApps.list"
        },
        "get": {
          "id": "dfareporting.mobileApps.get",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "description": "Gets one mobile app by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one account permission group by ID.",
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "id": "dfareporting.accountPermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list"
        },
        "insert": {
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "httpMethod": "POST"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/videoFormats",
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/videoFormats"
        },
        "get": {
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.get",
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}",
          "httpMethod": "GET",
          "description": "Gets one video format by ID."
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{profileId}/placementStrategies"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.update",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy."
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Inserts a new placement strategy."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID.",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete"
        },
        "list": {
          "id": "dfareporting.placementStrategies.list",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "POST",
          "description": "Inserts a new creative group.",
          "id": "dfareporting.creativeGroups.insert"
        },
        "list": {
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeGroups"
        },
        "get": {
          "description": "Gets one creative group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "id": "dfareporting.creativeGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}"
        },
        "patch": {
          "path": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch",
          "httpMethod": "PATCH"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placements": {
      "methods": {
        "insert": {
          "description": "Inserts a new placement.",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/placements",
          "flatPath": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/placements/generatetags",
          "flatPath": "userprofiles/{profileId}/placements/generatetags"
        },
        "list": {
          "path": "userprofiles/{profileId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{profileId}/placements"
        },
        "get": {
          "path": "userprofiles/{profileId}/placements/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.get",
          "flatPath": "userprofiles/{profileId}/placements/{id}",
          "httpMethod": "GET",
          "description": "Gets one placement by ID."
        },
        "update": {
          "path": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.update",
          "description": "Updates an existing placement.",
          "flatPath": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "description": "Retrieves a list of countries.",
          "flatPath": "userprofiles/{profileId}/countries",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/countries",
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get",
          "flatPath": "userprofiles/{profileId}/countries/{dartId}",
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "httpMethod": "GET",
          "description": "Gets one country by ID."
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/cities",
          "flatPath": "userprofiles/{profileId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.cities.list"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of platform types.",
          "id": "dfareporting.platformTypes.list",
          "path": "userprofiles/{profileId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/platformTypes",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one platform type by ID.",
          "id": "dfareporting.platformTypes.get",
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query",
          "description": "Retrieves list of report dimension values for a list of filters."
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "description": "Gets one postal code by ID.",
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of postal codes.",
          "id": "dfareporting.postalCodes.list"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "id": "dfareporting.contentCategories.list",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new content category.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.insert",
          "flatPath": "userprofiles/{profileId}/contentCategories"
        },
        "delete": {
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.contentCategories.update"
        },
        "get": {
          "id": "dfareporting.contentCategories.get",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/contentCategories/{id}"
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/sites",
          "flatPath": "userprofiles/{profileId}/sites",
          "description": "Inserts a new site.",
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{profileId}/sites",
          "description": "Updates an existing site.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites/{id}",
          "flatPath": "userprofiles/{profileId}/sites/{id}",
          "id": "dfareporting.sites.get",
          "httpMethod": "GET"
        },
        "patch": {
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/sites",
          "path": "userprofiles/{profileId}/sites",
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites",
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging."
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaUpload": true,
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "description": "Inserts a new creative asset.",
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/mobileCarriers",
          "path": "userprofiles/{profileId}/mobileCarriers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of mobile carriers.",
          "id": "dfareporting.mobileCarriers.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "id": "dfareporting.mobileCarriers.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID."
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountPermissions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.get",
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}"
        },
        "list": {
          "description": "Retrieves the list of account permissions.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountPermissions",
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{profileId}/accountPermissions"
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "description": "Inserts a new advertiser.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser by ID.",
          "id": "dfareporting.advertisers.get",
          "flatPath": "userprofiles/{profileId}/advertisers/{id}"
        },
        "patch": {
          "path": "userprofiles/{profileId}/advertisers",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser.",
          "id": "dfareporting.advertisers.update",
          "httpMethod": "PUT"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{profileId}/advertisers"
        }
      }
    }
  },
  "name": "dfareporting",
  "version": "v4",
  "revision": "20230210",
  "basePath": "/dfareporting/v4/",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "kind": "discovery#restDescription",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "canonicalName": "Dfareporting",
  "ownerDomain": "google.com",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "ownerName": "Google"
}
