{
  "name": "vault",
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "servicePath": "",
  "title": "Google Vault API",
  "revision": "20230221",
  "rootUrl": "https://vault.googleapis.com/",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/vault",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "basePath": "",
  "canonicalName": "Vault",
  "kind": "discovery#restDescription",
  "version": "v1",
  "id": "vault:v1",
  "ownerName": "Google",
  "resources": {
    "matters": {
      "methods": {
        "count": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.count",
          "flatPath": "v1/matters/{matterId}:count",
          "description": "Counts the accounts processed by the specified query.",
          "httpMethod": "POST",
          "path": "v1/matters/{matterId}:count"
        },
        "close": {
          "id": "vault.matters.close",
          "flatPath": "v1/matters/{matterId}:close",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "description": "Closes the specified matter. Returns the matter with updated state.",
          "path": "v1/matters/{matterId}:close",
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets the specified matter.",
          "id": "vault.matters.get",
          "path": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/matters/{matterId}"
        },
        "delete": {
          "id": "vault.matters.delete",
          "path": "v1/matters/{matterId}",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "DELETE"
        },
        "undelete": {
          "path": "v1/matters/{matterId}:undelete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.undelete",
          "flatPath": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "description": "Undeletes the specified matter. Returns the matter with updated state."
        },
        "removePermissions": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "description": "Removes an account as a matter collaborator.",
          "path": "v1/matters/{matterId}:removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "id": "vault.matters.removePermissions",
          "httpMethod": "POST"
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters",
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "id": "vault.matters.create",
          "flatPath": "v1/matters"
        },
        "update": {
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "PUT",
          "path": "v1/matters/{matterId}",
          "id": "vault.matters.update",
          "flatPath": "v1/matters/{matterId}"
        },
        "addPermissions": {
          "httpMethod": "POST",
          "description": "Adds an account as a matter collaborator.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:addPermissions",
          "id": "vault.matters.addPermissions",
          "flatPath": "v1/matters/{matterId}:addPermissions"
        },
        "list": {
          "description": "Lists matters the requestor has access to.",
          "path": "v1/matters",
          "flatPath": "v1/matters",
          "id": "vault.matters.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "reopen": {
          "id": "vault.matters.reopen",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "path": "v1/matters/{matterId}:reopen",
          "flatPath": "v1/matters/{matterId}:reopen"
        }
      },
      "resources": {
        "savedQueries": {
          "methods": {
            "get": {
              "description": "Retrieves the specified saved query.",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "id": "vault.matters.savedQueries.get",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "create": {
              "id": "vault.matters.savedQueries.create",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "description": "Creates a saved query.",
              "httpMethod": "POST",
              "path": "v1/matters/{matterId}/savedQueries"
            },
            "list": {
              "description": "Lists the saved queries in a matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.list",
              "flatPath": "v1/matters/{matterId}/savedQueries"
            },
            "delete": {
              "id": "vault.matters.savedQueries.delete",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes the specified saved query.",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}"
            }
          }
        },
        "holds": {
          "methods": {
            "get": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.get",
              "httpMethod": "GET",
              "description": "Gets the specified hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}"
            },
            "delete": {
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "DELETE",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.delete",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}"
            },
            "addHeldAccounts": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "httpMethod": "POST",
              "id": "vault.matters.holds.addHeldAccounts"
            },
            "removeHeldAccounts": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "id": "vault.matters.holds.removeHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request."
            },
            "create": {
              "flatPath": "v1/matters/{matterId}/holds",
              "id": "vault.matters.holds.create",
              "description": "Creates a hold in the specified matter.",
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "update": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "PUT",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.update"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/holds",
              "description": "Lists the holds in a matter.",
              "flatPath": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.holds.list"
            }
          },
          "resources": {
            "accounts": {
              "methods": {
                "list": {
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "id": "vault.matters.holds.accounts.list",
                  "httpMethod": "GET",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold."
                },
                "create": {
                  "id": "vault.matters.holds.accounts.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
                  "httpMethod": "POST",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts"
                },
                "delete": {
                  "description": "Removes an account from a hold.",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "id": "vault.matters.holds.accounts.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}"
                }
              }
            }
          }
        },
        "exports": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "id": "vault.matters.exports.get",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Gets an export."
            },
            "list": {
              "id": "vault.matters.exports.list",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/exports",
              "description": "Lists details about the exports in the specified matter.",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/exports"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "description": "Deletes an export.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.exports.delete"
            },
            "create": {
              "path": "v1/matters/{matterId}/exports",
              "httpMethod": "POST",
              "flatPath": "v1/matters/{matterId}/exports",
              "id": "vault.matters.exports.create",
              "description": "Creates an export.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "path": "v1/{+name}:cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "httpMethod": "POST",
          "id": "vault.operations.cancel"
        },
        "get": {
          "id": "vault.operations.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "id": "vault.operations.delete",
          "path": "v1/{+name}"
        },
        "list": {
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "id": "vault.operations.list",
          "flatPath": "v1/operations",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operatio[...]"
        }
      }
    }
  },
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "baseUrl": "https://vault.googleapis.com/",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        }
      }
    }
  }
}
