{
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "basePath": "/dfareporting/v4/",
  "protocol": "rest",
  "revision": "20230210",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "version": "v4",
  "name": "dfareporting",
  "resources": {
    "countries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/countries",
          "flatPath": "userprofiles/{profileId}/countries",
          "id": "dfareporting.countries.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of countries."
        },
        "get": {
          "description": "Gets one country by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "flatPath": "userprofiles/{profileId}/countries/{dartId}"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/cities",
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of cities, possibly filtered."
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountActiveAdSummaries.get",
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID.",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "httpMethod": "GET"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "id": "dfareporting.creativeAssets.insert",
          "supportsMediaUpload": true,
          "description": "Inserts a new creative asset.",
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.delete",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "description": "Deletes an existing placement strategy."
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement strategy by ID.",
          "id": "dfareporting.placementStrategies.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}"
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.list"
        },
        "insert": {
          "id": "dfareporting.placementStrategies.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{profileId}/placementStrategies"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "id": "dfareporting.targetingTemplates.list",
          "path": "userprofiles/{profileId}/targetingTemplates"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.update",
          "path": "userprofiles/{profileId}/targetingTemplates"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}",
          "id": "dfareporting.targetingTemplates.get",
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID."
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "POST"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sizes/{id}",
          "httpMethod": "GET",
          "description": "Gets one size by ID.",
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{profileId}/sizes/{id}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/sizes",
          "httpMethod": "GET",
          "id": "dfareporting.sizes.list",
          "path": "userprofiles/{profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI."
        },
        "insert": {
          "id": "dfareporting.sizes.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sizes",
          "description": "Inserts a new size.",
          "flatPath": "userprofiles/{profileId}/sizes",
          "httpMethod": "POST"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "path": "userprofiles/{profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission by ID.",
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}",
          "id": "dfareporting.userRolePermissions.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of languages.",
          "flatPath": "userprofiles/{profileId}/languages",
          "id": "dfareporting.languages.list"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of metros.",
          "id": "dfareporting.metros.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/metros"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/browsers",
          "httpMethod": "GET",
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{profileId}/browsers",
          "description": "Retrieves a list of browsers."
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "path": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "flatPath": "userprofiles/{profileId}/advertisers/{advertiserId}/invoices",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "update": {
          "id": "dfareporting.accounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/accounts",
          "flatPath": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account."
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "GET",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/accounts/{id}",
          "path": "userprofiles/{profileId}/accounts/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accounts.get"
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{profileId}/directorySites",
          "flatPath": "userprofiles/{profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new directory site."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "id": "dfareporting.directorySites.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/directorySites/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one directory site by ID."
        },
        "list": {
          "id": "dfareporting.directorySites.list",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/directorySites",
          "flatPath": "userprofiles/{profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "GET",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.list"
        },
        "update": {
          "path": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.update",
          "description": "Updates an existing subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/subaccounts"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/subaccounts"
        },
        "get": {
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.insert",
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "description": "Gets one remarketing list by ID."
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "description": "Gets one postal code by ID.",
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}",
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.get"
        },
        "list": {
          "id": "dfareporting.postalCodes.list",
          "path": "userprofiles/{profileId}/postalCodes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "description": "Retrieves a list of postal codes."
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "POST",
          "description": "Inserts a new campaign."
        },
        "get": {
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns/{id}",
          "description": "Gets one campaign by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/campaigns/{id}"
        },
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.list"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PATCH"
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/campaigns"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "description": "Gets one mobile carrier by ID.",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/mobileCarriers",
          "path": "userprofiles/{profileId}/mobileCarriers",
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers."
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PATCH"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.list"
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID."
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag"
        },
        "update": {
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "id": "dfareporting.inventoryItems.get",
          "description": "Gets one inventory item by ID."
        },
        "list": {
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "id": "dfareporting.inventoryItems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "path": "userprofiles/{profileId}/platformTypes",
          "description": "Retrieves a list of platform types.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "id": "dfareporting.platformTypes.get",
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "id": "dfareporting.creatives.get",
          "description": "Gets one creative by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "flatPath": "userprofiles/{profileId}/creatives/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.insert",
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.creatives.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/creatives",
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics."
        },
        "list": {
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "id": "dfareporting.creatives.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging."
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}",
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "id": "dfareporting.placementGroups.patch",
          "path": "userprofiles/{profileId}/placementGroups"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "description": "Inserts a new placement group."
        },
        "update": {
          "description": "Updates an existing placement group.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update",
          "path": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/files",
          "flatPath": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "description": "Lists files for a user profile."
        },
        "get": {
          "id": "dfareporting.files.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "path": "reports/{reportId}/files/{fileId}"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.get",
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permission groups.",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "id": "dfareporting.accountPermissionGroups.list"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups",
          "description": "Inserts a new creative group.",
          "httpMethod": "POST",
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{profileId}/creativeGroups"
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "update": {
          "description": "Updates an existing creative group.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{profileId}/creativeGroups"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "id": "dfareporting.creativeGroups.get",
          "httpMethod": "GET",
          "description": "Gets one creative group by ID.",
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}"
        },
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging."
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/regions",
          "id": "dfareporting.regions.list",
          "description": "Retrieves a list of regions.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/regions"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.get",
          "description": "Gets one operating system version by ID.",
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "patch": {
          "id": "dfareporting.contentCategories.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "description": "Updates an existing content category.",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.update"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.insert",
          "description": "Inserts a new content category."
        },
        "get": {
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "id": "dfareporting.contentCategories.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "path": "userprofiles/{profileId}/contentCategories",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging."
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing dynamic targeting key.",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list"
        },
        "insert": {
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert"
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "description": "Deletes an existing event tag.",
          "id": "dfareporting.eventTags.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags/{id}"
        },
        "list": {
          "description": "Retrieves a list of event tags, possibly filtered.",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.list"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one event tag by ID.",
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/eventTags/{id}"
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.update",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/eventTags",
          "id": "dfareporting.eventTags.insert",
          "description": "Inserts a new event tag."
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/projects/{id}",
          "id": "dfareporting.projects.get",
          "httpMethod": "GET",
          "description": "Gets one project by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/projects",
          "flatPath": "userprofiles/{profileId}/projects",
          "id": "dfareporting.projects.list",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging ."
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments."
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch",
          "flatPath": "userprofiles/{profileId}/remarketingLists"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new remarketing list.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "path": "userprofiles/{profileId}/remarketingLists"
        },
        "list": {
          "id": "dfareporting.remarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/remarketingLists",
          "flatPath": "userprofiles/{profileId}/remarketingLists"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/remarketingLists/{id}",
          "id": "dfareporting.remarketingLists.get",
          "description": "Gets one remarketing list by ID."
        },
        "update": {
          "description": "Updates an existing remarketing list.",
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingLists"
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertisers/{id}",
          "id": "dfareporting.advertisers.get"
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "path": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.list",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser.",
          "httpMethod": "PUT"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "patch": {
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.patch"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field by ID.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "path": "userprofiles/{profileId}/creativeFields/{id}"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "id": "dfareporting.creativeFields.delete",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.list",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields",
          "description": "Updates an existing creative field.",
          "id": "dfareporting.creativeFields.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/creativeFields"
        }
      }
    },
    "userRoles": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/userRoles",
          "description": "Inserts a new user role."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/userRoles",
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging."
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "id": "dfareporting.userRoles.delete",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "description": "Gets one user role by ID.",
          "id": "dfareporting.userRoles.get",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics."
        },
        "update": {
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserLandingPages.list",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.get",
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "patch": {
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserLandingPages.patch",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "list": {
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "id": "dfareporting.orderDocuments.list",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "id": "dfareporting.orderDocuments.get",
          "description": "Gets one order document by ID.",
          "httpMethod": "GET"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions.",
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST"
        },
        "batchinsert": {
          "description": "Inserts conversions.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.update",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues"
        },
        "delete": {
          "id": "dfareporting.creativeFieldValues.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "description": "Deletes an existing creative field value."
        },
        "get": {
          "description": "Gets one creative field value by ID.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}"
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging."
        }
      }
    },
    "reports": {
      "methods": {
        "get": {
          "id": "dfareporting.reports.get",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "insert": {
          "id": "dfareporting.reports.insert",
          "description": "Creates a report.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.reports.list",
          "description": "Retrieves list of reports.",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "delete": {
          "description": "Deletes a report by its ID.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.delete"
        },
        "patch": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates an existing report. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.patch"
        },
        "run": {
          "description": "Runs a report.",
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates a report.",
          "id": "dfareporting.reports.update",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "PUT"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "POST"
            }
          }
        },
        "files": {
          "methods": {
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Lists files for a report.",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files"
            },
            "get": {
              "id": "dfareporting.reports.files.get",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "supportsMediaDownload": true,
              "httpMethod": "GET",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
            }
          }
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.accountUserProfiles.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account user profile by ID.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}"
        },
        "list": {
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.list",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "id": "dfareporting.accountUserProfiles.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "path": "userprofiles/{profileId}/accountUserProfiles"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "description": "Inserts a new account user profile."
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "id": "dfareporting.orders.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one order by ID.",
          "id": "dfareporting.orders.get",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/changeLogs",
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of change logs. This method supports paging.",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{profileId}/changeLogs/{id}",
          "description": "Gets one change log by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "description": "Gets one advertiser group by ID."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "description": "Deletes an existing advertiser group.",
          "httpMethod": "DELETE"
        },
        "update": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserGroups.update",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert",
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.patch",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics."
        }
      }
    },
    "placements": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement.",
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT",
          "id": "dfareporting.placements.update"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "POST",
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement."
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/placements"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "id": "dfareporting.placements.generatetags",
          "path": "userprofiles/{profileId}/placements/generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/placements/generatetags"
        },
        "get": {
          "description": "Gets one placement by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements/{id}",
          "flatPath": "userprofiles/{profileId}/placements/{id}"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "patch": {
          "id": "dfareporting.floodlightConfigurations.patch",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "get": {
          "description": "Gets one floodlight configuration by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "id": "dfareporting.floodlightConfigurations.get",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates",
          "id": "dfareporting.billingRates.list",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "path": "userprofiles/{profileId}/billingProfiles/{billingProfileId}/billingRates"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/ads",
          "path": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list"
        },
        "patch": {
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads",
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "PATCH",
          "id": "dfareporting.ads.patch"
        },
        "insert": {
          "description": "Inserts a new ad.",
          "path": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.insert",
          "httpMethod": "POST"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/ads/{id}",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/ads/{id}",
          "id": "dfareporting.ads.get"
        },
        "update": {
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "PUT",
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad."
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "id": "dfareporting.accountPermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountPermissions",
          "path": "userprofiles/{profileId}/accountPermissions",
          "description": "Retrieves the list of account permissions."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}",
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{profileId}/accountPermissions/{id}"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.get",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.get",
          "description": "Gets one connection type by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "path": "userprofiles/{profileId}/connectionTypes/{id}"
        },
        "list": {
          "path": "userprofiles/{profileId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "flatPath": "userprofiles/{profileId}/connectionTypes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "id": "dfareporting.operatingSystems.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/operatingSystems",
          "description": "Retrieves a list of operating systems."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}",
          "description": "Gets one video format by ID."
        },
        "list": {
          "description": "Lists available video formats.",
          "path": "userprofiles/{profileId}/videoFormats",
          "flatPath": "userprofiles/{profileId}/videoFormats",
          "id": "dfareporting.videoFormats.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sites": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.list",
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{profileId}/sites/{id}",
          "id": "dfareporting.sites.get",
          "path": "userprofiles/{profileId}/sites/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.sites.insert",
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{profileId}/sites",
          "path": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "update": {
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{profileId}/sites",
          "description": "Updates an existing site.",
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing site. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/sites",
          "path": "userprofiles/{profileId}/sites"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity group by ID.",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups"
        },
        "update": {
          "description": "Updates an existing floodlight activity group.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.update",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.list",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging."
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "update": {
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{profileId}/billingProfiles",
          "httpMethod": "PUT",
          "id": "dfareporting.billingProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/billingProfiles"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.billingProfiles.get",
          "flatPath": "userprofiles/{profileId}/billingProfiles/{id}",
          "path": "userprofiles/{profileId}/billingProfiles/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one billing profile by ID."
        },
        "list": {
          "path": "userprofiles/{profileId}/billingProfiles",
          "flatPath": "userprofiles/{profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.list"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}",
          "id": "dfareporting.userProfiles.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID."
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles"
        }
      }
    }
  },
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "title": "Campaign Manager 360 API",
  "canonicalName": "Dfareporting",
  "id": "dfareporting:v4",
  "fullyEncodeReservedExpansion": true,
  "servicePath": "dfareporting/v4/"
}
