{
  "basePath": "/dfareporting/v3.5/",
  "kind": "discovery#restDescription",
  "version": "v3.5",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "canonicalName": "Dfareporting",
  "id": "dfareporting:v3.5",
  "protocol": "rest",
  "revision": "20230210",
  "discoveryVersion": "v1",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "servicePath": "dfareporting/v3.5/",
  "title": "Campaign Manager 360 API",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v3.5/",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  },
  "resources": {
    "subaccounts": {
      "methods": {
        "insert": {
          "description": "Inserts a new subaccount.",
          "path": "userprofiles/{profileId}/subaccounts",
          "id": "dfareporting.subaccounts.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/subaccounts"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/subaccounts"
        },
        "update": {
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "path": "userprofiles/{profileId}/subaccounts",
          "flatPath": "userprofiles/{profileId}/subaccounts",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "httpMethod": "GET",
          "description": "Gets one subaccount by ID.",
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{profileId}/subaccounts/{id}"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "description": "Gets one inventory item by ID.",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}"
        },
        "list": {
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.inventoryItems.list",
          "httpMethod": "GET"
        }
      }
    },
    "sites": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/sites/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/sites/{id}",
          "id": "dfareporting.sites.get",
          "description": "Gets one site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{profileId}/sites",
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{profileId}/sites",
          "httpMethod": "POST"
        },
        "update": {
          "id": "dfareporting.sites.update",
          "description": "Updates an existing site.",
          "flatPath": "userprofiles/{profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/sites",
          "httpMethod": "PUT"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "id": "dfareporting.floodlightActivityGroups.insert",
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Gets one floodlight activity group by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.get",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.patch"
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group.",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PUT"
        }
      }
    },
    "eventTags": {
      "methods": {
        "update": {
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/eventTags",
          "path": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag.",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID.",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}"
        },
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "flatPath": "userprofiles/{profileId}/eventTags/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an existing event tag."
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/eventTags"
        },
        "list": {
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered."
        },
        "insert": {
          "path": "userprofiles/{profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{profileId}/eventTags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "flatPath": "userprofiles/{profileId}/accountPermissions/{id}",
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{profileId}/accountPermissions/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{profileId}/accountPermissions",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{profileId}/accountPermissions"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "insert": {
          "path": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "description": "Inserts a new targeting template.",
          "httpMethod": "POST",
          "id": "dfareporting.targetingTemplates.insert"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/targetingTemplates/{id}",
          "id": "dfareporting.targetingTemplates.get",
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one targeting template by ID.",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update"
        },
        "list": {
          "id": "dfareporting.targetingTemplates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/targetingTemplates"
        }
      }
    },
    "accounts": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accounts",
          "flatPath": "userprofiles/{profileId}/accounts",
          "description": "Updates an existing account.",
          "httpMethod": "PUT",
          "id": "dfareporting.accounts.update"
        },
        "get": {
          "description": "Gets one account by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accounts.get",
          "path": "userprofiles/{profileId}/accounts/{id}",
          "flatPath": "userprofiles/{profileId}/accounts/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accounts"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accounts",
          "id": "dfareporting.accounts.list"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "description": "Updates an existing remarketing list share.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update"
        },
        "get": {
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list share by remarketing list ID.",
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "flatPath": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/remarketingListShares"
        }
      }
    },
    "campaigns": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "update": {
          "description": "Updates an existing campaign.",
          "path": "userprofiles/{profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{profileId}/campaigns"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns",
          "httpMethod": "POST",
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{profileId}/campaigns"
        },
        "get": {
          "description": "Gets one campaign by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.get",
          "flatPath": "userprofiles/{profileId}/campaigns/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/campaigns/{id}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{profileId}/campaigns"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{profileId}/metros",
          "flatPath": "userprofiles/{profileId}/metros",
          "id": "dfareporting.metros.list"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "description": "Retrieves a list of operating system versions.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "path": "userprofiles/{profileId}/operatingSystemVersions"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "description": "Gets one operating system version by ID.",
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "id": "dfareporting.operatingSystemVersions.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/languages",
          "id": "dfareporting.languages.list",
          "description": "Retrieves a list of languages.",
          "path": "userprofiles/{profileId}/languages"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group."
        },
        "patch": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups"
        },
        "get": {
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.get",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}"
        },
        "insert": {
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{profileId}/advertiserGroups"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/advertiserGroups/{id}",
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations"
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "description": "Retrieves a list of regions.",
          "id": "dfareporting.regions.list",
          "flatPath": "userprofiles/{profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/regions"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeGroups.list"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative group by ID.",
          "id": "dfareporting.creativeGroups.get",
          "flatPath": "userprofiles/{profileId}/creativeGroups/{id}"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing creative group.",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "POST",
          "description": "Inserts a new creative group.",
          "id": "dfareporting.creativeGroups.insert",
          "path": "userprofiles/{profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "description": "Gets one change log by ID.",
          "flatPath": "userprofiles/{profileId}/changeLogs/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/changeLogs/{id}"
        },
        "list": {
          "path": "userprofiles/{profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{profileId}/changeLogs"
        }
      }
    },
    "reports": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Creates a report.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "id": "dfareporting.reports.patch",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing report. This method supports patch semantics."
        },
        "get": {
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get",
          "httpMethod": "GET"
        },
        "run": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.run",
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.reports.update",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates a report."
        },
        "list": {
          "description": "Retrieves list of reports.",
          "httpMethod": "GET",
          "id": "dfareporting.reports.list",
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions."
            }
          }
        },
        "files": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Lists files for a report.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            },
            "get": {
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "id": "dfareporting.reports.files.get",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "description": "Gets one project by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.get",
          "path": "userprofiles/{profileId}/projects/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{id}"
        },
        "list": {
          "path": "userprofiles/{profileId}/projects",
          "flatPath": "userprofiles/{profileId}/projects",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.list",
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.accountUserProfiles.insert",
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update"
        },
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "GET"
        },
        "patch": {
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.accountUserProfiles.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "description": "Gets one account user profile by ID.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{id}"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "description": "Deletes an existing dynamic targeting key.",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.get",
          "path": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "flatPath": "reports/{reportId}/files/{fileId}"
        },
        "list": {
          "id": "dfareporting.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Lists files for a user profile.",
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/files"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "description": "Updates existing conversions.",
          "id": "dfareporting.conversions.batchupdate"
        },
        "batchinsert": {
          "description": "Inserts conversions.",
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{profileId}/userRolePermissionGroups"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/placementGroups",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{profileId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update"
        },
        "get": {
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementGroups/{id}",
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{profileId}/placementGroups",
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}"
        },
        "update": {
          "path": "userprofiles/{profileId}/placementStrategies",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy."
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placementStrategies"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement strategy by ID.",
          "id": "dfareporting.placementStrategies.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/placementStrategies/{id}",
          "path": "userprofiles/{profileId}/placementStrategies/{id}"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/placementStrategies",
          "path": "userprofiles/{profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.insert",
          "description": "Inserts a new placement strategy.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update",
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging."
        },
        "patch": {
          "id": "dfareporting.creativeFieldValues.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value. This method supports patch semantics."
        },
        "get": {
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "id": "dfareporting.creativeFieldValues.delete"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/connectionTypes/{id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "description": "Gets one connection type by ID.",
          "id": "dfareporting.connectionTypes.get"
        },
        "list": {
          "path": "userprofiles/{profileId}/connectionTypes",
          "flatPath": "userprofiles/{profileId}/connectionTypes",
          "id": "dfareporting.connectionTypes.list",
          "description": "Retrieves a list of connection types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "description": "Inserts a new remarketing list."
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/remarketingLists/{id}",
          "id": "dfareporting.remarketingLists.get",
          "path": "userprofiles/{profileId}/remarketingLists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.remarketingLists.patch"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "GET",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list.",
          "flatPath": "userprofiles/{profileId}/remarketingLists",
          "path": "userprofiles/{profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "httpMethod": "PUT"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "path": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "description": "Retrieves a list of cities, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/cities",
          "id": "dfareporting.cities.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/cities"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "generatetag": {
          "flatPath": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivities.generatetag",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates a tag for a floodlight activity."
        },
        "patch": {
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{profileId}/floodlightActivities"
        },
        "insert": {
          "path": "userprofiles/{profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivities.list",
          "flatPath": "userprofiles/{profileId}/floodlightActivities"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.floodlightActivities.delete",
          "description": "Deletes an existing floodlight activity.",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}"
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "description": "Gets one floodlight activity by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/floodlightActivities/{id}"
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{profileId}/directorySites",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/directorySites",
          "description": "Inserts a new directory site."
        },
        "list": {
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/directorySites"
        },
        "get": {
          "path": "userprofiles/{profileId}/directorySites/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/directorySites/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.list",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creativeFields"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "path": "userprofiles/{profileId}/creativeFields",
          "id": "dfareporting.creativeFields.insert",
          "description": "Inserts a new creative field.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFields.delete",
          "description": "Deletes an existing creative field."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/creativeFields"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creativeFields/{id}",
          "description": "Gets one creative field by ID.",
          "id": "dfareporting.creativeFields.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID.",
          "id": "dfareporting.mobileCarriers.get",
          "flatPath": "userprofiles/{profileId}/mobileCarriers/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/mobileCarriers",
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers.",
          "path": "userprofiles/{profileId}/mobileCarriers",
          "httpMethod": "GET"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of postal codes.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/postalCodes",
          "flatPath": "userprofiles/{profileId}/postalCodes",
          "id": "dfareporting.postalCodes.list",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.postalCodes.get",
          "description": "Gets one postal code by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "flatPath": "userprofiles/{profileId}/postalCodes/{code}"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/sizes/{id}",
          "id": "dfareporting.sizes.get",
          "httpMethod": "GET",
          "description": "Gets one size by ID.",
          "flatPath": "userprofiles/{profileId}/sizes/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/sizes",
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "path": "userprofiles/{profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list"
        },
        "insert": {
          "id": "dfareporting.sizes.insert",
          "flatPath": "userprofiles/{profileId}/sizes",
          "path": "userprofiles/{profileId}/sizes",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size."
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert",
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "httpMethod": "POST"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "description": "Gets one operating system by DART ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.get"
        },
        "list": {
          "description": "Retrieves a list of operating systems.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/operatingSystems"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/videoFormats",
          "id": "dfareporting.videoFormats.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/videoFormats",
          "description": "Lists available video formats."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/videoFormats/{id}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "id": "dfareporting.videoFormats.get",
          "description": "Gets one video format by ID."
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/countries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/countries",
          "httpMethod": "GET",
          "id": "dfareporting.countries.list",
          "description": "Retrieves a list of countries."
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "description": "Gets one country by ID.",
          "flatPath": "userprofiles/{profileId}/countries/{dartId}"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get",
          "flatPath": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "path": "userprofiles"
        }
      }
    },
    "placements": {
      "methods": {
        "update": {
          "id": "dfareporting.placements.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/placements",
          "description": "Updates an existing placement."
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/placements/generatetags",
          "flatPath": "userprofiles/{profileId}/placements/generatetags",
          "httpMethod": "POST",
          "id": "dfareporting.placements.generatetags"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.insert",
          "description": "Inserts a new placement.",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/placements"
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/placements",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/placements",
          "id": "dfareporting.placements.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement. This method supports patch semantics.",
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{profileId}/placements",
          "path": "userprofiles/{profileId}/placements"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/placements/{id}",
          "description": "Gets one placement by ID.",
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{profileId}/placements/{id}"
        }
      }
    },
    "advertisers": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.patch"
        },
        "list": {
          "path": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser.",
          "flatPath": "userprofiles/{profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "description": "Inserts a new advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/advertisers"
        },
        "get": {
          "description": "Gets one advertiser by ID.",
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/advertisers/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new landing page.",
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.list",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.get",
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creatives": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "POST"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.update",
          "flatPath": "userprofiles/{profileId}/creatives",
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/creatives/{id}",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "httpMethod": "GET",
          "description": "Gets one creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get"
        },
        "list": {
          "path": "userprofiles/{profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.list"
        },
        "patch": {
          "path": "userprofiles/{profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.creatives.patch",
          "flatPath": "userprofiles/{profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics."
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types.",
          "path": "userprofiles/{profileId}/platformTypes",
          "flatPath": "userprofiles/{profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "flatPath": "userprofiles/{profileId}/platformTypes/{id}",
          "id": "dfareporting.platformTypes.get"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "id": "dfareporting.ads.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/ads"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/ads",
          "path": "userprofiles/{profileId}/ads"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{profileId}/ads/{id}",
          "flatPath": "userprofiles/{profileId}/ads/{id}"
        },
        "update": {
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad.",
          "id": "dfareporting.ads.update"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new ad.",
          "path": "userprofiles/{profileId}/ads",
          "flatPath": "userprofiles/{profileId}/ads",
          "id": "dfareporting.ads.insert",
          "httpMethod": "POST"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "httpMethod": "DELETE"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.contentCategories.patch",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/contentCategories"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "id": "dfareporting.contentCategories.insert",
          "description": "Inserts a new content category."
        },
        "get": {
          "id": "dfareporting.contentCategories.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/contentCategories/{id}",
          "description": "Gets one content category by ID."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.list",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/contentCategories",
          "path": "userprofiles/{profileId}/contentCategories",
          "description": "Updates an existing content category.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.update"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.browsers.list",
          "description": "Retrieves a list of browsers.",
          "path": "userprofiles/{profileId}/browsers",
          "flatPath": "userprofiles/{profileId}/browsers",
          "httpMethod": "GET"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "id": "dfareporting.floodlightConfigurations.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "description": "Gets one floodlight configuration by ID.",
          "flatPath": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.get"
        }
      }
    },
    "userRoles": {
      "methods": {
        "patch": {
          "path": "userprofiles/{profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/userRoles"
        },
        "delete": {
          "description": "Deletes an existing user role.",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}",
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "id": "dfareporting.userRoles.get",
          "flatPath": "userprofiles/{profileId}/userRoles/{id}"
        },
        "list": {
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{profileId}/userRoles",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing user role.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "id": "dfareporting.userRoles.update"
        },
        "insert": {
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{profileId}/userRoles",
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "POST",
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of user role permissions, possibly filtered."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/userRolePermissions/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "description": "Gets one user role permission by ID.",
          "id": "dfareporting.userRolePermissions.get"
        }
      }
    },
    "orderDocuments": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.orderDocuments.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "description": "Gets one order document by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orderDocuments.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "httpMethod": "GET",
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orderDocuments"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.list",
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/mobileApps"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "description": "Gets one mobile app by ID.",
          "flatPath": "userprofiles/{profileId}/mobileApps/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get"
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "id": "dfareporting.orders.get",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "description": "Gets one order by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "id": "dfareporting.orders.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "ownerName": "Google",
  "name": "dfareporting",
  "fullyEncodeReservedExpansion": true
}
