{
  "fullyEncodeReservedExpansion": true,
  "revision": "20230227",
  "kind": "discovery#restDescription",
  "version_module": true,
  "servicePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        }
      }
    }
  },
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "ownerName": "Google",
  "basePath": "",
  "discoveryVersion": "v1",
  "resources": {
    "customBiddingAlgorithms": {
      "methods": {
        "uploadScript": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "httpMethod": "GET",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object."
        },
        "get": {
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "description": "Gets a custom bidding algorithm."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful."
        },
        "list": {
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v2/customBiddingAlgorithms",
          "httpMethod": "GET",
          "path": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "flatPath": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "path": "v2/customBiddingAlgorithms",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "description": "Gets a custom bidding script.",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "partners": {
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "httpMethod": "GET"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner.",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST"
                }
              }
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "delete": {
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a site from a channel.",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites",
                  "id": "displayvideo.partners.channels.sites.create",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "httpMethod": "POST",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "id": "displayvideo.partners.channels.sites.replace"
                },
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit"
                },
                "list": {
                  "id": "displayvideo.partners.channels.sites.list",
                  "description": "Lists sites in a channel.",
                  "path": "v2/partners/{+partnerId}/channels/{+channelId}/sites",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnersId}/channels/{channelsId}/sites"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "id": "displayvideo.partners.channels.patch",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels/{channelId}",
              "flatPath": "v2/partners/{partnersId}/channels/{channelId}",
              "httpMethod": "PATCH"
            },
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/partners/{partnersId}/channels/{channelsId}",
              "id": "displayvideo.partners.channels.get",
              "path": "v2/partners/{+partnerId}/channels/{+channelId}",
              "httpMethod": "GET"
            },
            "create": {
              "path": "v2/partners/{+partnerId}/channels",
              "flatPath": "v2/partners/{partnersId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "id": "displayvideo.partners.channels.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels",
              "flatPath": "v2/partners/{partnersId}/channels",
              "id": "displayvideo.partners.channels.list"
            }
          }
        }
      },
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "v2/partners/{partnersId}",
          "path": "v2/partners/{+partnerId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.get",
          "description": "Gets a partner."
        },
        "editAssignedTargetingOptions": {
          "path": "v2/partners/{+partnerId}:editAssignedTargetingOptions",
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/partners/{partnersId}:editAssignedTargetingOptions"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v2/partners",
          "path": "v2/partners",
          "id": "displayvideo.partners.list",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter."
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "patch": {
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "httpMethod": "PATCH",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "description": "Gets a first and third party audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}"
        },
        "create": {
          "id": "displayvideo.firstAndThirdPartyAudiences.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "path": "v2/firstAndThirdPartyAudiences",
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "flatPath": "v2/firstAndThirdPartyAudiences",
          "path": "v2/firstAndThirdPartyAudiences"
        },
        "editCustomerMatchMembers": {
          "httpMethod": "POST",
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "path": "v2/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers"
        }
      }
    },
    "inventorySourceGroups": {
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "list": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "GET",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "httpMethod": "POST",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "delete": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "httpMethod": "DELETE",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group."
            },
            "bulkEdit": {
              "httpMethod": "POST",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      },
      "methods": {
        "create": {
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v2/inventorySourceGroups",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "flatPath": "v2/inventorySourceGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "description": "Deletes an inventory source group.",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.delete"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.patch",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySourceGroups/{inventorySourceGroupId}"
        },
        "list": {
          "flatPath": "v2/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.list",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v2/inventorySourceGroups",
          "httpMethod": "GET"
        },
        "get": {
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.get",
          "description": "Gets an inventory source group.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists targeting options of a given type."
            },
            "get": {
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "httpMethod": "GET",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a single targeting option.",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}"
            },
            "search": {
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Searches for targeting options of a given type based on the given search terms."
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v2/inventorySources/{+inventorySourceId}",
          "description": "Gets an inventory source.",
          "id": "displayvideo.inventorySources.get",
          "flatPath": "v2/inventorySources/{inventorySourcesId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.patch",
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "path": "v2/inventorySources/{+inventorySourceId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful."
        },
        "list": {
          "id": "displayvideo.inventorySources.list",
          "flatPath": "v2/inventorySources",
          "path": "v2/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results."
        },
        "editInventorySourceReadWriteAccessors": {
          "flatPath": "v2/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "path": "v2/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "id": "displayvideo.inventorySources.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySources",
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "httpMethod": "POST",
          "path": "v2/inventorySources"
        }
      }
    },
    "customLists": {
      "methods": {
        "list": {
          "path": "v2/customLists",
          "id": "displayvideo.customLists.list",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/customLists",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v2/customLists/{+customListId}",
          "id": "displayvideo.customLists.get",
          "flatPath": "v2/customLists/{customListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom list."
        }
      }
    },
    "users": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v2/users/{usersId}",
          "description": "Gets a user.",
          "path": "v2/users/{+userId}",
          "httpMethod": "GET",
          "id": "displayvideo.users.get"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "PATCH",
          "path": "v2/users/{+userId}",
          "id": "displayvideo.users.patch",
          "description": "Updates an existing user. Returns the updated user if successful.",
          "flatPath": "v2/users/{usersId}"
        },
        "list": {
          "id": "displayvideo.users.list",
          "flatPath": "v2/users",
          "path": "v2/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful.",
          "flatPath": "v2/users",
          "path": "v2/users",
          "id": "displayvideo.users.create"
        },
        "bulkEditAssignedUserRoles": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "path": "v2/users/{+userId}:bulkEditAssignedUserRoles",
          "flatPath": "v2/users/{usersId}:bulkEditAssignedUserRoles",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles."
        },
        "delete": {
          "flatPath": "v2/users/{usersId}",
          "description": "Deletes a user.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users/{+userId}",
          "id": "displayvideo.users.delete"
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "flatPath": "download/{downloadId}",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.download",
          "path": "download/{+resourceName}"
        },
        "upload": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "flatPath": "media/{mediaId}",
          "path": "media/{+resourceName}",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "httpMethod": "POST",
          "id": "displayvideo.media.upload",
          "supportsMediaUpload": true
        }
      }
    },
    "sdfdownloadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "path": "v2/{+name}",
              "flatPath": "v2/sdfdownloadtasks/operations/{operationsId}",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/sdfdownloadtasks",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "path": "v2/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create"
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "description": "Gets a combined audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/combinedAudiences/{+combinedAudienceId}",
          "httpMethod": "GET",
          "flatPath": "v2/combinedAudiences/{combinedAudiencesId}",
          "id": "displayvideo.combinedAudiences.get"
        },
        "list": {
          "id": "displayvideo.combinedAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/combinedAudiences",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "path": "v2/combinedAudiences"
        }
      }
    },
    "advertisers": {
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                }
              }
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "get": {
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}"
            },
            "listAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.insertionOrders.listAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}:listAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:listAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.insertionOrders.list",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful."
            },
            "create": {
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.insertionOrders.create"
            },
            "delete": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "httpMethod": "DELETE",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Deletes an assigned targeting option from an insertion order. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEGATIVE_KEYWORD_LIST` * `TARGETING_TYPE_OPE[...]",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.delete",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "create": {
                      "description": "Assigns a targeting option to an insertion order. Returns the assigned targeting option if successful. Supported targeting types: * `TARGETING_TYPE_AGE_RANGE` * `TARGETING_TYPE_BROWSER` * `TARGETING_TYPE_CATEGORY` * `TARGETING_TYPE_CHANNEL` * `TARGETING_TYPE_DEVICE_MAKE_MODEL` * `TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION` * `TARGETING_TYPE_ENVIRONMENT` * `TARGETING_TYPE_GENDER` * `TARGETING_TYPE_KEYWORD` * `TARGETING_TYPE_LANGUAGE` * `TARGETING_TYPE_NEG[...]",
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.create",
                      "httpMethod": "POST",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "httpMethod": "GET",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get",
                      "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Gets a single targeting option assigned to an insertion order."
                    }
                  }
                }
              }
            }
          }
        },
        "youtubeAdGroupAds": {
          "methods": {
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds/{youtubeAdGroupAdsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds/{+youtubeAdGroupAdId}",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.get",
              "httpMethod": "GET",
              "description": "Gets a YouTube ad group ad."
            },
            "list": {
              "description": "Lists YouTube ad group ads.",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.youtubeAdGroupAds.list",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds",
              "httpMethod": "GET"
            }
          }
        },
        "campaigns": {
          "methods": {
            "delete": {
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.delete"
            },
            "listAssignedTargetingOptions": {
              "description": "Lists assigned targeting options of a campaign across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}:listAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}:listAssignedTargetingOptions",
              "id": "displayvideo.advertisers.campaigns.listAssignedTargetingOptions"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Gets a campaign.",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}"
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list"
            },
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.patch",
              "httpMethod": "PATCH"
            },
            "create": {
              "id": "displayvideo.advertisers.campaigns.create",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to a campaign for a specified targeting type.",
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.list"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a campaign.",
                      "id": "displayvideo.advertisers.campaigns.targetingTypes.assignedTargetingOptions.get"
                    }
                  }
                }
              }
            }
          }
        },
        "youtubeAdGroups": {
          "methods": {
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups",
              "httpMethod": "GET",
              "description": "Lists YouTube ad groups.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.youtubeAdGroups.list",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups"
            },
            "bulkListAdGroupAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.youtubeAdGroups.bulkListAdGroupAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple YouTube ad groups across targeting types. Inherieted assigned targeting options are not included.",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "httpMethod": "GET",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}",
              "description": "Gets a YouTube ad group.",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.youtubeAdGroups.get"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    },
                    "get": {
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "id": "displayvideo.advertisers.creatives.delete"
            },
            "list": {
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "flatPath": "v2/advertisers/{advertisersId}/creatives"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "PATCH",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.patch",
              "description": "Updates an existing creative. Returns the updated creative if successful."
            },
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.creatives.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a creative.",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.creatives.create",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "flatPath": "v2/advertisers/{advertisersId}/creatives"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/assets",
              "supportsMediaUpload": true,
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "id": "displayvideo.advertisers.assets.upload",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/assets"
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID."
            },
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch"
            },
            "list": {
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists"
            },
            "delete": {
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "replace": {
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace"
                },
                "bulkEdit": {
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit"
                },
                "list": {
                  "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "GET"
                },
                "delete": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}"
                },
                "create": {
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                }
              }
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites.",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:replace"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "description": "Deletes a site from a channel."
                },
                "create": {
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites"
                },
                "bulkEdit": {
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit"
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}/sites"
                }
              }
            }
          },
          "methods": {
            "create": {
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "id": "displayvideo.advertisers.channels.create"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.get",
              "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET"
            },
            "list": {
              "id": "displayvideo.advertisers.channels.list",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "path": "v2/advertisers/{+advertiserId}/channels"
            },
            "patch": {
              "id": "displayvideo.advertisers.channels.patch",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "patch": {
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}"
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "id": "displayvideo.advertisers.manualTriggers.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required.",
              "httpMethod": "GET"
            },
            "create": {
              "id": "displayvideo.advertisers.manualTriggers.create",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful."
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "id": "displayvideo.advertisers.manualTriggers.get",
              "description": "Gets a manual trigger."
            },
            "activate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "httpMethod": "POST",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "id": "displayvideo.advertisers.manualTriggers.activate"
            },
            "deactivate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deactivates a manual trigger.",
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate"
            }
          }
        },
        "lineItems": {
          "methods": {
            "generateDefault": {
              "description": "Creates a new line item with settings (including targeting) inherited from the insertion order and an `ENTITY_STATUS_DRAFT` entity_status. Returns the newly created line item if successful. There are default values based on the three fields: * The insertion order's insertion_order_type * The insertion order's automation_type * The given line_item_type",
              "id": "displayvideo.advertisers.lineItems.generateDefault",
              "path": "v2/advertisers/{+advertiserId}/lineItems:generateDefault",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:generateDefault"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.create",
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems"
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "bulkListAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple line items across targeting types."
            },
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.get",
              "description": "Gets a line item.",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkUpdate": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "id": "displayvideo.advertisers.lineItems.bulkUpdate"
            },
            "delete": {
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            },
            "bulkEditAssignedTargetingOptions": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetin[...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "httpMethod": "POST"
            },
            "duplicate": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful.",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * CreateLineItemAssignedTargetingOption * DeleteLineItemAssignedTargetingOption",
              "id": "displayvideo.advertisers.lineItems.patch",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get"
                    },
                    "create": {
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * DeleteLineItemAssignedTargetingOption",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to a line item."
                    },
                    "delete": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdate * UpdateLineItem * CreateLineItemAssignedTargetingOption",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete"
                    }
                  }
                }
              }
            }
          }
        },
        "locationLists": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "id": "displayvideo.advertisers.locationLists.patch",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListId}"
            },
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/locationLists"
            },
            "list": {
              "description": "Lists location lists based on a given advertiser id.",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "GET"
            },
            "get": {
              "path": "v2/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "description": "Gets a location list.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "id": "displayvideo.advertisers.locationLists.get"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "create": {
                  "description": "Creates an assignment between a location and a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "httpMethod": "POST",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "httpMethod": "GET",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Lists locations assigned to a location list.",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "description": "Deletes the assignment between a location and a location list.",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete"
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/invoices",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "flatPath": "v2/advertisers/{advertisersId}/invoices",
              "id": "displayvideo.advertisers.invoices.list",
              "httpMethod": "GET"
            },
            "lookupInvoiceCurrency": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "flatPath": "v2/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency"
            }
          }
        }
      },
      "methods": {
        "listAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v2/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions"
        },
        "editAssignedTargetingOptions": {
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "httpMethod": "POST",
          "flatPath": "v2/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.editAssignedTargetingOptions"
        },
        "audit": {
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "httpMethod": "GET",
          "flatPath": "v2/advertisers/{advertisersId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}:audit",
          "id": "displayvideo.advertisers.audit"
        },
        "create": {
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.create",
          "path": "v2/advertisers",
          "flatPath": "v2/advertisers",
          "httpMethod": "POST"
        },
        "patch": {
          "path": "v2/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.patch",
          "flatPath": "v2/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful."
        },
        "list": {
          "flatPath": "v2/advertisers",
          "id": "displayvideo.advertisers.list",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "path": "v2/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.get",
          "path": "v2/advertisers/{+advertiserId}",
          "description": "Gets an advertiser.",
          "flatPath": "v2/advertisers/{advertisersId}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "DELETE",
          "flatPath": "v2/advertisers/{advertisersId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "id": "displayvideo.advertisers.delete",
          "path": "v2/advertisers/{+advertiserId}"
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "path": "v2/floodlightGroups/{+floodlightGroupId}",
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/floodlightGroups/{floodlightGroupsId}",
          "id": "displayvideo.floodlightGroups.get"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v2/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "flatPath": "v2/floodlightGroups/{floodlightGroupId}",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful."
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "flatPath": "v2/guaranteedOrders",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "path": "v2/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editGuaranteedOrderReadAccessors": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits read advertisers of a guaranteed order.",
          "httpMethod": "POST",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors"
        },
        "get": {
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "description": "Gets a guaranteed order.",
          "httpMethod": "GET",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "id": "displayvideo.guaranteedOrders.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.patch",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "httpMethod": "PATCH",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}"
        },
        "list": {
          "path": "v2/guaranteedOrders",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "flatPath": "v2/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.list",
          "httpMethod": "GET"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "v2/googleAudiences/{googleAudiencesId}",
          "description": "Gets a Google audience.",
          "path": "v2/googleAudiences/{+googleAudienceId}",
          "id": "displayvideo.googleAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.googleAudiences.list",
          "path": "v2/googleAudiences",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "flatPath": "v2/googleAudiences"
        }
      }
    }
  },
  "title": "Display & Video 360 API",
  "batchPath": "batch",
  "id": "displayvideo:v2",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "ownerDomain": "google.com",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "protocol": "rest",
  "name": "displayvideo",
  "version": "v2",
  "canonicalName": "Display Video",
  "documentationLink": "https://developers.google.com/display-video/",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items."
}
